### ISSUE TITLE
Parámetros ilegales para las operaciones

### ISSUE THREAD

**Issue by sgvasquez** [IIC2133-PUC/2018-1#1]
Hola! 

En la función _insert_ que tenemos que implementar, ¿qué ocurre cuando el indice está fuera del arreglo/lista? Por ejemplo, pongo en una lista ligada un elemento en la posición N muy grande. ¿Tira error? ¿Apunta al penúltimo elemento de la lista, aunque este tenga un índice muy pequeño?

De la misma forma, si tengo un arreglo de tamaño (por ejemplo) 16, y quiero asignar un elemento en la posición 42, ¿Genero tantos arrays como sean necesarios y lleno de vacío entremedio? 

Saludos, gracias!

**Comment by Ghoeb** [comment]
Hola, buena pregunta. Ambos casos que planteas son operaciones ilegales, por lo que no se espera que tu estructura las maneje. Pueden asumir que en todo momento que se van a usar correctamente las estructuras.

**Comment by Ghoeb** [comment]
Como norma general no cierren issues, así quedan visibles para el resto. Nosotros nos encargaremos de cerrarlas cuando sea pertinente 😄

**Comment by yoavnavon** [comment]
Sumandome sobre la funcion insert,  si tengo un el arreglo [1,2], y quiero insertar el elemento 3 en la posicion 1, el arreglo quedará [1,3,2] o se reemplaza quedando [1,3]?

Saludos y gracias!

**Comment by alopez7** [comment]
Queda 1, 3, 2

**Comment by PabloAbara** [comment]
Y no habrá un comando para reemplazar algún valor intermedio entonces? (Bueno, se puede componer entre un insert y un delete de todos modos... pero para saber si hay que agregarlo). 

Gracias

**Comment by asimonv** [comment]
Qué pasa con los números negativos? Tenemos que soportarlos?

**Comment by alopez7** [comment]
No es necesario que soporten números negativos

**Comment by asimonv** [comment]
@alopez7 gracias!

**Comment by ignaciohermosillacornejo** [comment]
En el insert, las posiciones van de 0...n-1 o de 1...n?

**Comment by alopez7** [comment]
0 al n, puedes insertar en n+1 posiciones distintas

**Comment by ignaciohermosillacornejo** [comment]
No me queda claro, ayudame con estos casos para clarificar porfa. Digamos que A = [5, 6, 7, 8]
- insert(A, 9, 0), entonces A = 
- insert(A, 9, 1), entonces A = 
- insert(A, 9, 4), entonces A =

**Comment by alopez7** [comment]
[9, 5, 6, 7, 8]
[5, 9, 6, 7, 8]
[5, 6, 7, 8, 9]

**Comment by ignaciohermosillacornejo** [comment]
muchas gracias @alopez7
