### ISSUE TITLE
Análisis empíricos para test

### ISSUE THREAD

**Issue by TamaraCucumides** [IIC2133-PUC/2018-1#100]
Hola, para el informe debo entregar métricas de rendimientos para todos los test de todas las dificultades, o basta con mostrar algunos para compararlos?

Gracias.

**Comment by alopez7** [comment]
Se debe notar como cambian las métricas de desempeño con respecto a las distintas variables. Por ejemplo si mides el tiempo vs  tamaño del puzzle, entonces necesitas usar todos los test que tengas, si revisas como cambia respecto a las podas, entonces tambien sería bueno tener en varios test. Evidentemente que si un test se demora muchisimo sin podas, entonces le das un timeout y dices que se demora mas del límite nomás
