### ISSUE TITLE
Poda adicional

### ISSUE THREAD

**Issue by TamaraCucumides** [IIC2133-PUC/2018-1#102]
Acerca de la poda adicional, la idea es que sea útil al implementarla en conjunto a las dos otras podas? O sirve también alguna poda que de cierta manera reemplace a alguna de las ya propuestas?

Pregunto esto porque entre más complejo se hace el programa, imaginemos con las dos podas anteriores y la propagacion, hay partes de el que se vuelven inutiles.

P. ej: Si se implementa bien propagacion, la poda de degree ya no sirve. Pero la poda en si misma es útil. 

La pregunta entonces es, al pensar en la utilidad de la "nueva poda propuesta" estamos pensando en el problema sin podas? el problema con alguna poda? el problema con ambas podas? o el problema con ambas podas, propagación, heurística, etc ?

**Comment by alopez7** [comment]
Si una poda queda inutil entonces mejor sácala

**Comment by TamaraCucumides** [comment]
@alopez7 eso lo tengo claro, pero en el informe, para discutir la utilidad de podas adicionales?

Puedo proponer una poda y comentar en que casos sería util y en que casos no?

Pregunto porque en la tarea dice "proponer una poda adicional y justificar su utilidad "

**Comment by alopez7** [comment]
Entonces usa la poda y justifíca con los resultados que no vale la pena usarla.

**Comment by Rodancoci** [comment]
Osea, ¿la idea es que la nueva poda propuesta se implementaría en conjunto con las podas ya mencionadas en el enunciado? Es decir, ¿tiene que hacer algo que no esté considerado por las otras dos podas?

**Comment by Ghoeb** [comment]
Exacto, algo independiente de las otras dos podas, que también sea consecuencia de las restricciones originales.

Hint: Los dos escenarios de podas planteados en el enunciado surgen de las restricciones de vecinos y de grupos, pero no del hecho de que todas las celdas de la orilla son amarillas...
