### ISSUE TITLE
Conjuntos disjuntos

### ISSUE THREAD

**Issue by lfbesa** [IIC2133-PUC/2018-1#104]
¿De donde podemos estudiar conjuntos disjuntos? ¿Hay alguna guía o libro que sirva?

**Comment by eiherrera** [comment]
Hola! Si mal no recuerdo, yo estudié esa materia del [Cormen](http://ressources.unisciel.fr/algoprog/s00aaroot/aa00module1/res/%5BCormen-AL2011%5DIntroduction_To_Algorithms-A3.pdf), con lo que me quedó muy claro.

**Comment by yadran** [comment]
Así es, el Cormen et al.; y la mayoría de los buenos textos
sobre algoritmos y estructuras de datos.  --Yadran
