### ISSUE TITLE
MST - óptimo global - definición

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2133-PUC/2018-1#105]
Hola,

Hay un par de conceptos que no me quedan claros:

1) En la def. de MST no entiendo bien bien a que se refieren con la parte del mínimo, que dice que no existe un árbol de cobertura con un menor costo total: ¿Que es ese costo total? ¿La suma delos costos de las aristas simplemente?

2) Tampoco entiendo a que se refieren cuando Prim, por ejemplo, no siempre llega al óptimo global. ¿Que define un optimo global o local?

3) Dados loa anteriores, deduzco que Prim no siempre llega a un MST, y Kruskal no me queda claro (pensaría que si). ¿Estoy bien en lo que deduzco?

Gracias!

**Comment by yadran** [comment]
1. El costo del árbol es efectivamente la suma de los costos de las aristas
que forman el árbol (que es un subconjunto de
las aristas que forman el grafo).

2 y 3. Tanto Prim como Kruskal son algoritmos que resuelven el problema del
árbol de cobertura de costo mínimo (o MST).

--Yadran

2018-05-29 21:28 GMT-04:00 jorgeriesco <notifications@github.com>:

**Comment by Ghoeb** [comment]
En ningún minuto se dijo que Prim no llegaba al óptimo: parece que confundiste con que Prim es un **algoritmo codicioso**, y ese tipo de algoritmos no necesariamente encuentra el óptimo (pero en este caso si!)

Cuando hablamos de óptimo global vs óptimo local, es lo mismo que se ve en cálculo cuando queremos minimizar una función que no es convexa: los mínimos y máximos de la función ocurren donde la derivada es 0, pero (asumiendo que existen) solo hay un valor más grande que toda la función, y uno solo más pequeño que toda la función (por eso reciben el nombre de globales). Si partimos de un punto en el gráfico, y nos movemos en la dirección opuesta al gradiente (es decir, la dirección en la que la función decrece más rapido), no siempre vamos a llegar al mínimo global: podemos encontrarnos con un mínimo local, y sin revisar todos los valores posibles de la función, no tenemos como saber la diferencia. Espero que la imagen te recuerde de que estoy hablando:

![image](https://user-images.githubusercontent.com/5317897/40710288-7fb70930-63b5-11e8-84f2-b0bebe481522.png)

Podríamos hacer la analogía entre MST y la optimización convexa: partiendo desde cualquier punto, moverse en la dirección que más nos acerca al mínimo nos lleva eventualmente a una solución. La diferencia es que este tipo de problemas no son continuos: el valor de la función salta según si incluimos o no una arista. La gracia es que sabemos exactamente cuantas debemos incluir, por lo que, agregar la arista más pequeña en cada paso es la solución en este caso.
