### ISSUE TITLE
Pasos Minimos Tests

### ISSUE THREAD

**Issue by yoavnavon** [IIC2133-PUC/2018-1#109]
Hola! Me preguntaba si pudieran subir cuanto sería la cantidad de pasos minima de cada test, para ver si mi programa funciona correctamente. Algunos tests se puede ver a simple vista el óptimo, pero en algunos de los mas grandes es más difícil.

**Comment by alopez7** [comment]
Hola, la cantidad de pasos de cada test son:

Test 0: 5
Test 1: 11
Test 2: 14
Test 3: 17
Test 4: 9
Test 5: 13
Test 6: 19
Test 7: 13
Test 8: 47
Test 9: 20

**Comment by yoavnavon** [comment]
Gracias!!

**Comment by alopez7** [comment]
Voy a dejar abierta esta issue porque le puede servir a otros alumnos

**Comment by yoavnavon** [comment]
Puede ser que a todas les falte 1 paso? Por ejemplo el test 4 tiene 10 piedras, sería imposible hacerlo en 9 pasos.

**Comment by alopez7** [comment]
Si, toda la razon. Lei mal el output. Gracias

**Comment by fcgfaura** [comment]
Es válido que las naves que están en los bordes cuando disparan les llega de vuelta la bala y giran?, o es un error de la página ? El test 9 con 9,10 se soluciona jajaja.

**Comment by alopez7** [comment]
Es un error de la página, le aviso altiro a eugenio. Cual es la secuencia de pasos que ingresaste y en que test?
@eiherrera

**Comment by eiherrera** [comment]
Solucionado! Espero no haber llevado a pasar algo al arreglarlo, así que avisen si encuentran otro bug. Gracias!
