### ISSUE TITLE
Dudas de como empezar

### ISSUE THREAD

**Issue by sebacruzd** [IIC2133-PUC/2018-1#11]
Hola,

Falté a la ayudantía (un error) y no estoy entendiendo muy bien cómo usar los archivos que tenemos.
Se podría hacer un resumen de lo que se habló en la ayudantía?

Gracias!

**Comment by Ghoeb** [comment]
¿Probaste compilar los ejemplos como dice la guía de instalación?

**Comment by sebacruzd** [comment]
Sí, después de eso no sé exactamente para qué son los archivos creados o de qué manera usarlos.
Se crean varios archivos y carpetas, pero no sé qué hacer con ellos.

**Comment by alopez7** [comment]
Los archivos .h tienen la descripción de la estructura (la debes completar tu) y los headers de las funciones, los cuales no debes modificar.
En los archivos .c se completan efectivamente las funciones definidas en el .h y puedes definir otras funciones para el uso interno de ese archivo.
En el main está la función main la cual se llama al principio de tu programa

**Comment by sebacruzd** [comment]
Gracias!
