### ISSUE TITLE
Librerías

### ISSUE THREAD

**Issue by gacuchac** [IIC2133-PUC/2018-1#110]
Puedo usar openssl/sha.h para hashear los tableros?

**Comment by alopez7** [comment]
No, la idea es que ustedes hagan su propia función de hash.
Es recomendable usar zobrist sobre las navesby asteroides.
Saludos

**Comment by gacuchac** [comment]
super, te pasaste

**Comment by gacuchac** [comment]
puedo usar string.h?

**Comment by alopez7** [comment]
Si

**Comment by lfbesa** [comment]
Se puede usar sprintf?

**Comment by lfbesa** [comment]
Se puede usar stdio.h?

**Comment by alopez7** [comment]
Si
