### ISSUE TITLE
Duda del bfs a aplicar

### ISSUE THREAD

**Issue by roy350** [IIC2133-PUC/2018-1#112]
Tengo un problema en el momento de elegir que nave usar para atacar, ya tengo tabla de hash implementada y me ahorro casos repetidos, el tema es que mi tarea funciona bien para los 3 primeros test, 0,1,2 en menos de 1 segundo, pero el test3 lo deje correr y da la respuesta correcta en 8 minutos, los demás se demoran más así que, no los he dejado terminar, y he visto los estados que entran y salen y están correctos, quizás la forma en que elijo que nave va a atacar, puede ser el problema, en un principio, probaba con la primera nave que pillaba, luego intente darle prioridades a que nave estaba más cercana de los distintos asteorides y no hubo mucho cambio, nose si debemos optimizarla de alguna forma en particular a parte de saltarse los casos repetidos, ya que si lo estoy haciendo y aun así se demora mucho, Muchas gracias

**Comment by alopez7** [comment]
Calcula cuantos estados estás explorando por nivel. Es posible que estés repitiendo estados.

**Comment by roy350** [comment]
Me podrias decir cuantos son los estados esperables? pondre los 3 primeros que son los que puedo resolver
test0 = 22
test1= 213
test2 = 8122

**Comment by alopez7** [comment]
Test 0 = 21
Test 1 = 185
Test 2 = 5084
Test 3 = 407208
Test 4 = 366171
Test 5 = 573754
Test 6 = 531529
Test 7 = 630247
Test 8 = 716270
Test 9 = 684343

Considera que mi programa termina cuando hace la operación que encuentra el estado final, no cuando saca el estado final de la cola. Esto evita que explore el ultimo nivel completo antes de terminar. Eso puede hacer la diferencia que tenemos.

**Comment by alopez7** [comment]
Todos los test en mi solucion toman menos de un segundo.
Estás copiando los estados completos para  guardarlos en la tabla de hash?

**Comment by roy350** [comment]
como? no entendi tu pregunta? a que te refieres con copiar los estados completos?

**Comment by alopez7** [comment]
En la tabla de hash se supone que guardas los estados en los que ya has estado para no repetir tantos estados al buscar. Puedes guardar el tablero completo (no es recomendable) o una reprecentación del tablero (los asteroides que quedan y las direcciones de las naves)

**Comment by roy350** [comment]
lo que hace mi tabla de hash en efecto es guardar el tablero completo, pero esa representacion como se realizaria? te refieres a que los espacios en blanco(5) los omita? o como?

**Comment by roy350** [comment]
alguna recomendacion, porque hice una representacion usando, una struct Position que tiene x,y y el numero que representa, y a lo agrego a un "puntero" para manejarlo similar a un arreglo, pero no mejora mucho el tiempo, que representación seria más eficiente?

**Comment by alopez7** [comment]
Yo recomiendo tener en la tabla y en la cola de BFS un struct que contenga un arreglo de direcciones de las naves (numero del 0 al 3) y un arrrglo de bools indicando si estan los ateroides

**Comment by rfenzo** [comment]
yo tambien estoy teniendo algunos problemas de tiempo y cantidad de estados. Para los test 0 a 3 tengo la misma cantidad de estados que los que indicaron arriba, aunque el test 3 se me demora 6 seg. El test 4 sin embargo genera más de 1.000.000 estados y no lo he podido terminar. @alopez7 , a que te refieres con " y un arrrglo de bools indicando si estan los ateroides " :/

**Comment by alopez7** [comment]
Digamos que hay 10 asteroides y 12 naves en el mapa.
Yo los enumero del 0 al 9 y 0 al 14 los tengo en dos arreglos junto con mi tablero. Luego, al guardar algo en la tabla creo un arreglo de ints para las direcciones (numeros del 0 al 3) y arreglos de bools para los asteroides indicando si el asteroide fue destruido o no.
De esta manera al comparar estados itero sobre los arreglos.

**Comment by roy350** [comment]
las direcciones de las respectivas naves y de los asteroides como las obtienes?

**Comment by rfenzo** [comment]
@alopez7 gracias, no hice exactamente lo que dijiste pero me sirvió para corregir unos errores. Ahora ya funciona

**Comment by alopez7** [comment]
@roy350 
Al principio tengo mi tablero con el estado inicial y creo los arreglos de celdas de las naves y los asteroides. Al aplicar operaciones sobre el tablero voy alterando estos arreglos, y al sacar un elemento de la cola cargo la información de los arreglos a mi tablero.

**Comment by fvandeputte** [comment]
Hola Antonio, tengo una duda: La tabla de Hash se usa para buscar de manera rápida si un estado ya fue visitado o no, verdad?
En un post anterior mencionaste recomendaste usar "zobrist" para hashear los tableros. Esto de las listas, reemplaza lo anterior?

Gracias!!

**Comment by alopez7** [comment]
No, la tabla es muy necesaria.
El rol de la tabla es determinar eficientemente si un estado ya fue visitado. 
Cada vez que descubres un estado tienes que consultar en la tabla si ya visitaste ese estado antes. En el caso de que el estado ya fue visitado, entonces lo ignoras. Sino, lo agregas a la tabla y lo metes a la cola de bfs.
Lo de los array

**Comment by alopez7** [comment]
Mañana estaré en la universidad respondiendo dudas. Ahí lo vemos. Enviaré un aviso por mail

**Comment by gacuchac** [comment]
A mi lo que me sirvio muchisimo fue no guardar los numeros en int si no en uint8. Con ese cambio, mi programa se demora 4 segundos para el peor test

**Comment by roy350** [comment]
como?? osea todo int que usaste lo hiciste con uint8?

**Comment by gacuchac** [comment]
Mi estado guarda el disparo x,y del estado anterior en 2 uint8, un arrrglo de naves como arreglo de uint8 y un puntero al estado anterior.
En el main use algunos ints pero solo fuera de los loops que ejecutan el bfs. Dentro de los loops, use solo uint8. Ojo, uint8 es solo para valores hasta 255

**Comment by roy350** [comment]
pero mi pregunta es, en un inicio tu tarea fue hecha con int y se te demoraba mucho? y al cambiarlo a uint8 tuviste el cambio significativo?

**Comment by gacuchac** [comment]
Si

**Comment by alopez7** [comment]
Es posible que esté funcionando lenta la tabla de hash. Puedes calcular la cantidad de coliciones o cosas de ese estilo.

**Comment by gacuchac** [comment]
Investiga la diferencia entre signed y unsigned. Tu computador lee el ultimo bit para saber si es positivo o negativo en signed pero en unsigned el ultim9 bit significa 1 o 0 × 2^n. Entonces si lo imprimes como int que es signed, el numero es positivo o negativo segun el bit a pesar que las operaciones en uint son siempre positivas. Positivo o negativo no es intrinseco depende de como se lee el numero. Es materia de arquitectura de computadores

**Comment by iqacevedo** [comment]
Hola,

Si sigues la recomendación de otra issue y lo imprimes con formato  %llu en vez de %d o %i vas a ver que si son números siempre positivos.

**Comment by roy350** [comment]
@alopez7 el test3 tengo 640466 colisiones supongo que eso es mucho, el largo de mi tabla es de 999999, nose que podria hacer para mejorarla

**Comment by moralillo** [comment]
Es muy lento usar una representación de string de el tablero como key del diccionario? De esta forma, solamente se comparan strings al buscar si el estado ya fue visitado.

**Comment by alopez7** [comment]
Si, es lento. Lo ideal es comparar por un hash de largo constante y si son iguales comparar por las direcciones de las naves y los asteroides

**Comment by moralillo** [comment]
No entendí lo de comparar por un largo constante. También lo hice comparando cantidades de naves en cada dirección y cantidad de asteroides, pero el tiempo era igual a si lo hacia comparando strings. No entiendo cual es esa diferencia en la búsqueda de un elemento en la tabla que lo hace tanto más eficiente. Tiene algo que ver con lo de los uint8?

**Comment by alopez7** [comment]
Lo primero siempre es comparar por el hash. Luego comparar por las direcciones de las naves y los asteroides. Si tu llegas y comparas por el tablero completo te va a tomar O(h*w), si lo haces de esta manera te va a tomar O(naves + asteroides). Y si tu hash distribuye bien, el costo de naves + asteroides solo se va a tener que hacer cuando efectivamente los estados son iguales o cuando hay una colisión en el hash.
