### ISSUE TITLE
get_random_number

### ISSUE THREAD

**Issue by gacuchac** [IIC2133-PUC/2018-1#113]
entrega siempre el mismo número: 1525778597845688323

**Comment by alopez7** [comment]
Voy a revisarlo. En qué sistema operativo estas trabajando?

**Comment by alopez7** [comment]
A mi me funciona bien. Si tienes problemas puedes usar rand(), es una funcion de C que retorna un numero random de 32 bits. Si quieres tener uno de 64 bits puedes hacer:
uint64_t number = (((uint64_t)rand())<<32) + rand();

**Comment by gacuchac** [comment]
ubuntu 18.04

**Comment by gacuchac** [comment]
rand() me da 1804289383 siempre

**Comment by eiherrera** [comment]
Podrías probar dándole el tiempo como valor al seed de rand. [Acá](https://stackoverflow.com/questions/1108780/why-do-i-always-get-the-same-sequence-of-random-numbers-with-rand) hay un ejemplo.
