### ISSUE TITLE
Hash table

### ISSUE THREAD

**Issue by tmorales1** [IIC2133-PUC/2018-1#114]
Nos podemos basa en algún diccionario de internet (implementación para C) y adaptarlo a nuestras necesidades?

**Comment by alopez7** [comment]
Si, mientras los implementes ustedes

**Comment by gacuchac** [comment]
quería usar un hashtable de largo 18446744073709551615 en que el numero zorbist que es un uint64_t es el key pero me tira un error de array is too large. Se que casi no voy a usar la memoria que estoy reservando pero era para buscar rápido. Hay alguna forma de hashear así? no quiero hacer un ABB.

**Comment by eiherrera** [comment]
¡Hola! Tengo algunas dudas: primero, ¿porqué quieres hacer un arreglo de ese tamaño? No es necesario hacer uno tan grande, de hecho, para el problema de la tarea es excesivamente grande. La velocidad de tu búsqueda, teniendo una buena función de hash y un arreglo de tamaño proporcional a los estados que vas a recorrer, no va a mejorar por incrementar el tamaño de tu arreglo. 

Segundo, no entiendo porqué piensas implementar un árbol de busqueda binario como solución a tu problema.

**Comment by alopez7** [comment]
Debes hacer una tabla de tamaño dinamico, asi cuando necesitas aumentar el tamaño duplicas el tamaño y pasas los datos denuna tabla a otra.
Si bien el hash de un estado puede ser muy grande, lanposición en la que va es hash % tamaño_ tabla, porblo que la tabla no tiene por que ser taaan grande

**Comment by gacuchac** [comment]
muchas gracias

**Comment by jpdattas** [comment]
Cual sería el factor de carga? o como se determina eso? nunca me quedó muy claro eso

**Comment by alopez7** [comment]
Eso lo puedes determinar tu experimentalmente. Normalmente 60-70% funciona bien

**Comment by jpdattas** [comment]
Usaré  60-70% entonces, gracias.
Pero hay alguna forma de sacar el factor de carga ideal por teoría? O eso escapa del ramo?

**Comment by alopez7** [comment]
La verdad se saca haciendo experimentos.
