### ISSUE TITLE
malloc(sizeof(uint64_t))

### ISSUE THREAD

**Issue by gacuchac** [IIC2133-PUC/2018-1#115]
no me funciona asignat espacio de memoria para variables del tipo uint64_t me aparece un error variable-sized object may not be initialized. Como puedo guardar mis valores sin asignarles memoria? o mejor, como puedo asignar memoria a mis valores del tipo uint64_t?

**Comment by alopez7** [comment]
Tienes que usar <stdint.h>

**Comment by alopez7** [comment]
Y se usa tal como un int normal

**Comment by alopez7** [comment]
uint64_t b = 16388362829;
uint64_t a = b*b;

**Comment by gacuchac** [comment]
se arreglo solo cuando cerre y volvi a abrir el atom.

**Comment by alopez7** [comment]
Atomicosas
