### ISSUE TITLE
Hash Zobrist

### ISSUE THREAD

**Issue by berrazuriz1** [IIC2133-PUC/2018-1#116]
Hay algo que no entiendo de este hashing. ¿por que es necesario hacer una tabla con números aleatorios para representar el estado del tablero? En teoría se debería poder numerar las casillas con las distintas posibilidades de piezas, solo tenemos que evitar repetir números.

**Comment by alopez7** [comment]
No es necesario usar zobrist, es mi sugerencia. Pueden usar el hash que quieran.

**Comment by berrazuriz1** [comment]
Si, si cacho, pero igual me surgió la duda de porque usa números random

**Comment by alopez7** [comment]
Porque distibuyen uniforme en la tabla, así tienes menos colisiones.

**Comment by berrazuriz1** [comment]
aaa  ya wena
