### ISSUE TITLE
get_random_number

### ISSUE THREAD

**Issue by sgvasquez** [IIC2133-PUC/2018-1#118]
No sé si será el comportamiento normal de la función, pero al llamar get_random_number n veces, siempre me entrega los mismos n numeros, sin importar la cantidad de veces que haga make -> ./solver

Por ejemplos, sin importar cuantas veces llame el programa, al llamar 10 numeros random, me arroja siempre

1525778597845688323
14629868571074490350
2078261572662367632
7358401772848389646
13252269741992521293
13669164227398947826
15283347160445955594
16666062205366614812
13379387420507447776
9529521304083583838

Es normal?

**Comment by alopez7** [comment]
Es porque no tiene una seed. No consideré que sea necesario darle una.
