### ISSUE TITLE
duda al agregar objeto a arreglos

### ISSUE THREAD

**Issue by sebawarrior** [IIC2133-PUC/2018-1#12]
Hola, tengo la siguiente duda: Si en un arreglo con tamaño fijo trato de agregarle o insertarte un objeto, o bien concatenar otra lista mas, entonces, en caso de excederme del tamaño del arreglo, qué se debe hacer con lo que se intenta agregar? o asumo que los tamaños van a calzar en los inputs para no pasarme? muchas gracias.

**Comment by alopez7** [comment]
Tienes que crear un arreglo nuevo y traspasar los datos.
Este arreglo tiene que crecer multiplicandolo por alguna constante (en general 2) para que no tengas que traspasar los datos todas las veces

**Comment by sebawarrior** [comment]
y al crear este arreglo nuevo, dejamos los otros arreglos intactos (en caso de concatenar)? y si agregamos o insertamos, al crear un nuevo arreglo que hacemos con el arreglo original? Muchas gracias!

**Comment by alopez7** [comment]
No se concatenan los arreglos, traspasas los datos de un arreglo al otro y liberas la memoria del arreglo viejo

**Comment by alopez7** [comment]
Aaaaa, entendí mal la pregunta. Ambos arreglos pasan a ser el mismo, y los otros se pierden

**Comment by berrazuriz1** [comment]
¿cuando dices que se pierden te refieres a que todo la memoria que se deja de usar la tengo que liberar cierto?

**Comment by alopez7** [comment]
Si tienes A =[0, 1, 2] y B = [3, 4]  y haces concatenate(A, B)
A debería ser igual a [0, 1, 2, 3, 4]
Y B debería ser null.
Parece un poco arbitrario pero tienes sentidobpara que la operación sea eficiente para listas ligadas

**Comment by berrazuriz1** [comment]
Si entendi eso, a lo que me refiero es si solo basta cn liberar la memoria de la lista B?
