### ISSUE TITLE
numeros random

### ISSUE THREAD

**Issue by roy350** [IIC2133-PUC/2018-1#120]
Hola! resulta que me dan algunos numeros random negativos y eso hace que mi programa se caiga cuando recorro mi arreglo, es normal que de numero negativos, o estou usando mal el random?

**Comment by alopez7** [comment]
Si guardas el numero como un uint64_t nunca debería ser negativo

**Comment by alopez7** [comment]
Para imprimirlo debe ser con %llu

**Comment by roy350** [comment]
es que me daba problema recibir el uint64_t en una funcion no entiendo porque

**Comment by alopez7** [comment]
Debes incluir <stding.h>
