### ISSUE TITLE
Rigurosidad en el Tiempo

### ISSUE THREAD

**Issue by tsuarezsaieh** [IIC2133-PUC/2018-1#121]
¿Que tan estricta serán con el tiempo de evaluación? En el enunciado dice que esperaran 10 segundos por cada test, pero mi programa resuelve el test 9 en ~15 segundos, ¿eso sería un 0 en ese test?

**Comment by alopez7** [comment]
El código lo corrige un programa. Si no termine en 10 segundos se tiene 0 en ese test

**Comment by nivek0o0** [comment]
Encuentro super penca que corrijan en base al tiempo. Los que usamos máquina virtual porque tenemos Windows (que supongo somos la mayoría) vemos mermado el tiempo de ejecución porque la máquina no ocupa toda la capacidad de procesamiento de la CPU así como tampoco la totalidad de la memoria.

Por otra parte, el tiempo no determina un correcto aprendizaje de los contenidos que vemos en el curso, que debería ser el objetivo de las evaluaciones. Creo que la correctitud de la respuesta de nuestro algoritmo debería estar por sobre la eficiencia, es decir, ambos aspectos deberían tener un peso en la nota.

**Comment by alopez7** [comment]
Todas las tareas se ejecutan en mi computador. Así que el computador en el que trabajen no les da una diferencia en el tiempo. En particular mi computador es nuevo y bueno por lo que tienen una ventaja en ese sentido.

Si no tubiera timeout algunas tareas aun estarían funcionando, y a no ser que se resuelva el halting problem no creo que se pueda mejorar el sistema.

Por mi parte intento tener test de distintas dificultades, por lo que una buena tarea debería resolver todos los test, una tarea mas o menos debería resolver aproximadamente la mitad y una mala tarea debería resolver solo los más fáciles. Además como ayudante hago una solución que está al nivel esperado de sus tareas y pruebo los test. Cada test de esta tarea se resuelve en menos de 2 segundos por mi solución por lo que tienen un rango de tiempo alto.

Dada la cantidad de alumnos y ayudantes es inviable corregir cada tarea individualmente por lo que lo mejor que podemos hacer es hacer un corrector automático.

**Comment by nivek0o0** [comment]
Entiendo perfectamente, pero mi problema es que los tests de ejemplo me corren entre 0 y 30 segundos, por lo que no tengo idea si es una ineficiencia de mi algoritmo o de mi computador(donde la VM ocupa un máximo de 35% de la CPU), y si en tu computador correrán más rápido.
Pero filo, ocuparé estos días adicionales viendo qué puedo optimizar. Gracias por el tiempo extra.

**Comment by PabloAbara** [comment]
@alopez7  y el criterio es el mismo si tengo "una operación extra" ? Me pasa con un test que tengo una operación innecesaria (por nada) 🤔 , pero destruye todo, es 0 también?

**Comment by alopez7** [comment]
Que test es? Creo que escribí mal uno. Creo que lo tienes bueno. En todo caso dar una solucion con pasos extra si está mal.

**Comment by PabloAbara** [comment]
Lamentablemente, sé que es un paso innecesario jajaja es el 9 creo (no es el corregido). En fin, gracias por la rápida respuesta!
