### ISSUE TITLE
Perdida de valores en estructuras contenidas

### ISSUE THREAD

**Issue by sgvasquez** [IIC2133-PUC/2018-1#122]
Hola! Para la tarea tengo (entre varias) dos estructuras: data (que dice la info del estado actual) y queuenode (que contiene data que va a estar en cola para ser observada)

Me pasa que cuando voy a insertar data en queuenode, los valores de data se "pierden" en el sentido que se vuelven cualquier cosa. Me explico:

Si tengo una instancia de data, al printear sus valores me da:
```
Hash: 4064473969056951599
reAst: 3
Pos ship 0: 2
Pos ship 1: 0
Pos ast 0: 4
Pos ast 1: 4
Pos ast 2: 4

```
Al hacer Queuenode->data = data (paso los valores uno a uno, ergo queuenode->data->hash = data->hash y así), y luego printear los valores de Queuenode->data, me da:
```
Hash: 140592807899512
reAst: 1348432296
Post ship 0: 1348432264
Post ship 1: 32734
Post ast 0: 1348432264
Post ast 1: 32734
Post ast 2: 11563568
```

No sé si me explico bien. Alguna idea de donde me equivoqué? 

Gracias!

**Comment by sebacruzd** [comment]
Una idea muy al aire, no estarás pasándole los punteros en vez de lo que apuntan?

**Comment by sgvasquez** [comment]
Al final era un problema de como estaba armando los nodos de la cola. Cuando vaciaba la cola ya instanciada se comportaba de forma extraña :)

Gracias!
