### ISSUE TITLE
Plazo Tarea 3

### ISSUE THREAD

**Issue by haroldmuller** [IIC2133-PUC/2018-1#123]
Hola, 
se que es encima de la entrega, pero habría la posibilidad de tener solo un día más para la entrega de la tarea 3? De antemano muchas gracias.

**Comment by alopez7** [comment]
La verdad no hay tiempo de semestre y ya fue recolectado

**Comment by jpdattas** [comment]
"ya fue recolectado"...
sale que la fecha de entrega es el "18/06/2018" "1 minuto pasadas las 23:59 horas del día de entrega"

**Comment by alopez7** [comment]
Ups, pensé que era para ayer. Entonces lo recolectaré denuevo hoy en la noche. En todo caso no se dará mas plazo.

**Comment by RodrigoBocazG** [comment]
Por favor reconsiderenlo :(. Es solo un día más el que pedimos

**Comment by dalliende** [comment]
O que se pueda entregar atrasado con penalizacion porfa

**Comment by TamaraCucumides** [comment]
Y unas 12 horas más? :D

**Comment by alopez7** [comment]
Hoy en la reunión de ayudantes se discutirá el plazo. Les aviso apenas lleguemos a una conclusión.

**Comment by iqacevedo** [comment]
Muchas gracias por considerarlo :)

**Comment by sguerra2** [comment]
Ya es oficial: se entrega este miércoles!! 😺 Mandamos un aviso
