### ISSUE TITLE
Problema al correr el programa

### ISSUE THREAD

**Issue by nachojarasaez** [IIC2133-PUC/2018-1#124]
![Uploading Captura de pantalla 2018-06-18 a la(s) 11.04.18.png…]()
Hola tengo el siguiente problema, aveces cuando corro el programa en distintos test me arroja el siguiente problemas: solver(11053,0x7fff8de90340) malloc: *** error for object 0x7fd22b4026a8: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
Luego al correrlo renuevo sin modificar nada ya no aparece el problema y funcionan correctamente los test. No se si influirá mucho en la corrección de mi tarea y nose como corregirlo.

**Comment by alopez7** [comment]
Chuta, nunca he visto ese error. Mi única recomendación es buscarlo en google... se que no es mucho pero no tengo idea que puede ser.
Sorry

**Comment by nachojarasaez** [comment]
Lo raro es que lo corro una vez y me sale eso, si ejecuto la segunda vez la misma linea, funciona perfecto. Puede afectar mucho en la nota de mi tarea?? Que he investigado y no he logrado solucionarlo.

**Comment by alopez7** [comment]
Trata de correr tu tarea con valgrind, tal vez te da más información. En cuanto a la evaluación si tu tarea falla tendrás el test malo, pero si funciona tendrás el test bueno
