### ISSUE TITLE
Error al compilar 

### ISSUE THREAD

**Issue by berrazuriz1** [IIC2133-PUC/2018-1#13]
Ayer me tope con un problema a la hora de compilar. Cuando compilo con "make", el comando como que compila solo el archivo arraylist.o y listas, y despues dice "Done compiling". Despues al tratar de ejecutar cualquier programa de la tarea desde ese mismo directorio (en donde esta el makefile), me dice "No such file or directory" y si lo trato de ejecutar llegando directamente al archivo me niega el permiso. La verdad es que he buscado soluciones en google y encontre un par que me deja correr los programas, pero luego me sale syntax error en el main.c, como que no reconociera que esta en escrito en c.

**Comment by alopez7** [comment]
Trata escribiendo make clean y despues make

**Comment by berrazuriz1** [comment]
ya se lo que paso, era una tontera. 
Gracias igual
