### ISSUE TITLE
Tiempo de ejecución con ventanas abiertas

### ISSUE THREAD

**Issue by sebawarrior** [IIC2133-PUC/2018-1#130]
Hola, me pasa que cuando corro los test, con ventanas o aplicaciones abiertas se demora más que si no las tuviera. Corregirán todo teniendo en cuenta este defecto? (Osea, sin ventanas, para que los programas no se demoren más)??

**Comment by alopez7** [comment]
Si, la idea es que esté toda mi cpu y memoria disponible

**Comment by sebawarrior** [comment]
Ya buenísimo! gracias!
