### ISSUE TITLE
Segmetation fault en ubuntu

### ISSUE THREAD

**Issue by nachojarasaez** [IIC2133-PUC/2018-1#131]
Hola quisiera saber que puede estar pasando. Trabaje mi tarea en Mac OS y al pasarme ubuntu y compilar me tira segmentation fault. Sabes porque puede estar pasando? (Hago prints en el main y  nisiquiera entra)

**Comment by nachojarasaez** [comment]
En Mac OS me funcionaba todo menos el test 9.

**Comment by alopez7** [comment]
Es comun que el intérprete de mac de C haga ciertas cosas para que tu
ptograma no se caiga cuando debería caerse. Es por eso que la plataforma de
trabajo oficial del curso es en linux. Ejecuta tu programa con valgrind y
te debería decir el problema.
