### ISSUE TITLE
Tarea 4 y horario ayudantía

### ISSUE THREAD

**Issue by alobatog** [IIC2133-PUC/2018-1#136]
Hola, tengo la duda de para qué sirve el archivo generator que viene en el repositorio de la tarea. Y a que hora será la ayudantía que se hara mañana?

**Comment by NachoCasta** [comment]
Según lo que vi ese código genera planetas aleatorios (tests) según los parámetros que te den. Lo deben haber usado para crear los tests que nos entregaron.

**Comment by alobatog** [comment]
Ahh, entonces no lo tenemos que usar en nuestro código. Gracias!

**Comment by alopez7** [comment]
Si, es para generar mas test por si quieren. Mañana la ayudantía/repaso es a las 2

**Comment by alobatog** [comment]
Gracias!
