### ISSUE TITLE
Violación de segmento en el fscanf

### ISSUE THREAD

**Issue by neberrios** [IIC2133-PUC/2018-1#139]
Al hacer fscanf para la primera fila del archivo me tira "violación de segmento", pero antes no me pasaba esto. Me empezó a fallar cuando probé con los tests grandes así que probé guardando los valores en long en vez de int, pero no cambio nada.
Qué puede ser?

**Comment by alopez7** [comment]
Lo único que se me ocurre es que el archivo es null

**Comment by neberrios** [comment]
Ya lo resolví. Gracias.
No era eso en todo caso jaja.
