### ISSUE TITLE
Error al asignar entero a la memoria

### ISSUE THREAD

**Issue by berrazuriz1** [IIC2133-PUC/2018-1#14]
Mi append del arraylist funciona perfecto, hasta que llego trato de ingresar el 4 elemento al array. En el main tengo esto:
 ```
ArrayList *list = arraylist_init();
  arraylist_append(list, 0);
 arraylist_append(list, 13);
  arraylist_append(list, 333);
  arraylist_append(list, 10);
```

Y en arraylist_append tengo esto:

 ```
int *aux_pointer = (list->pointer) + (list->count)*sizeof(int);
  *aux_pointer = element;
  printf("%d\n", *aux_pointer);
  printf("%p\n", aux_pointer);
  printf("%d\n", *aux_pointer);
  printf("%p\n", aux_pointer);
  list->count += 1;
```

Y esto al correrlo imprime todo bien hasta que me tira esto:
```
10
0x18f4060
942766128
0x18f4060
```

Claramente algo pasa entre medio de los prints en donde el valor que esta gurdado pasa de ser 10 (que es lo correcto) a ser 942766128. He probado de todo y nada funciona.

**Comment by alopez7** [comment]
Te estás complicando mucho con el puntero del arreglo. Puedes asignar el dato con list -> pointer[list -> count] = element

Es super mala practica hacer aritmetica de punteros
