### ISSUE TITLE
Arraylist duda conceptual

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2133-PUC/2018-1#15]
Hola, Tengo la siguiente duda:

Si tengo un Arraylist de tamaño 8 por ejemplo (en memoria), y he hecho solo 4 appends, ¿El largo teórico sería 4 u 8?
Profundizando más la pregunta, si yo inserto un elemento, ¿se debe poder permitir insertarlo en la posición 6, por ejemplo? ¿O solo se puede insertar entre los lugares ya ocupados (0 a 3)?

Ojalá se entienda la duda, gracias.

**Comment by srvasquez** [comment]
A mi me surgió también la duda de que por ejemplo si se puede insertar elementos en cualquier lugar de la lista, viendo el ejemplo de @jorgeriesco lo hacemos en la posición 6, el siguiente append donde deberíamos de agregar el elemento en los espacios vacíos antes del elemento del insert o después del elemento del insert.

**Comment by alopez7** [comment]
El largo del arraylist es 4, pero está usando un arreglo de largo 8. No debes permitir insertar en la posicion 6, ya que los datos deben estar compactos en el arreglo.
En python se usan arreglos dinámicos, funcionan parecido a los arraylist, pero uno como usuario no se entera que en verdad está usandi mas memoria.

**Comment by FranciscoLarach** [comment]
@alopez7 
Al inicializar un array, se dice que debe estar vacio. ¿ Esto significa que se ve como algo así [], o de un largo definido tipo [NULL, NULL, NULL....]? ¿ Y de ser la segunda, que largo debemos usar, o como referenciarlo?

**Comment by alopez7** [comment]
Al iniciar un arraylist no debe tener datos, pero debe tenet un arreglo del largo que te acomode.
Ese arreglo puede tener cualquier cosa, pero tú debes saber cuantos datos realmente tiene con la variable count
