### ISSUE TITLE
arraylist_delete

### ISSUE THREAD

**Issue by sebacruzd** [IIC2133-PUC/2018-1#16]
Hola,

Me surgió una duda al estar haciendo esta parte de la tarea.
Si bien es lógico que en la linkedlist al hacer el delete se borre el nodo B (nodos A -> B -> C) queden conectados los nodos A -> C, en los array no estoy seguro de cuál de las siguientes maneras debe hacerse.

Si mi array es así:
```c
[0, 1, 2, 3]
```
y borro la posición 1, de cuál de estas dos maneras debería quedar?
```c
[0, 0, 2, 3]  // solo eliminar la posición. Se considera que el 0 en la posición 1 es vacío.
             // Con esto quedaría con datasize 4

[0, 2, 3, 0]  // arrastrar los elementos una posición hacia atrás, se considera que el 0 en 
             // la posición 3 es vacío. Con esto quedaría con datasize 3
```

Gracias de antemano.

**Comment by nacosta-cl** [comment]
Tengo entendido que tu array quedaria como la segunda parte, pero sin el 0 al final (Queda como posicion invalida)
Algo como
[0,2,3]

**Comment by alopez7** [comment]
Tu arraylist debe tener todos sus datos de manera compacta.
Digamos que tienes un arraylist con 3 elementos y su arreglo tiene largo 4:
A = [1, 2, 3, cualquiercosa]
A.count = 3
A.size = 4

Si eliminas el elemento en la posicion 0, debería quedar:
A = [2, 3, cualquiercosa, cualquiercosa]
A.count = 2
A.size = 4
No debes rellenar con ceros, ya que puede haber confusiones. Por eso es importante tener una variable que sea count y otra que sea size

**Comment by sebacruzd** [comment]
Gracias @alopez7 !
