### ISSUE TITLE
uso de valgrind

### ISSUE THREAD

**Issue by sebawarrior** [IIC2133-PUC/2018-1#17]
Hola, quería preguntar acerca del uso de valgrind. La idea es que siempre salga cero en definitely lost, indirectly lost, possibly lost y still reachable? Pregunto pues intento usar valgrind y me tira algo por el estilo:

LEAK SUMMARY:
==13942==    definitely lost: 16 bytes in 1 blocks
==13942==    indirectly lost: 64 bytes in 4 blocks
==13942==      possibly lost: 0 bytes in 0 blocks
==13942==    still reachable: 0 bytes in 0 blocks
==13942==         suppressed: 0 bytes in 0 blocks
==13942== 
==13942== For counts of detected and suppressed errors, rerun with: -v
==13942== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)

Y la verdad no sé qué hacerle a mi codigo para que valgrind me lo acepte (aun cuando me imprime los valores en pantalla que pido). Hay que hacer free en el main de las cosas que uno hace? Muchas gracias

**Comment by alopez7** [comment]
Si, debe salir 0 en ambos.
Cuando tienes 0 leaks sale un mensaje que dice algo como. No leaks are possible
Si quieres saber de donde salen los leaks, puedes ejecutar tu código con valgrind --leak-check=full, o algo así

**Comment by sebawarrior** [comment]
Perfecto, pero eso lo estoy logrando al liberar la memoria desde el main, no dentro de las funciones a implementar (pues sino no tendría sentido implementar las funciones pues todo quedaría liberado). Ahora bien, si me aparece esto, cumple con el puntaje? o no debe tener errores de ningún tipo?

==16492== All heap blocks were freed -- no leaks are possible
==16492== 
==16492== For counts of detected and suppressed errors, rerun with: -v
==16492== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)

**Comment by alopez7** [comment]
Tienes que solucionar los errores. Valgrind te dice donde se encuentran
