### ISSUE TITLE
Tipo de Datos

### ISSUE THREAD

**Issue by gacuchac** [IIC2133-PUC/2018-1#18]
Hola, los tipos de datos que van en las listas son solo ints o pueden ser cualquier cosa? puede ser structs tambien? y mezclas de datos como [1, hola, 2.35, struct hola { char[10]={"h","o","l","a",}}]?

**Comment by gacuchac** [comment]
y mezclas de datos como [1, hola, 2.35, struct hola { char[10]={"h","o","l","a",}}]

**Comment by alopez7** [comment]
Solo ints
