### ISSUE TITLE
Duda con el free de listas ligadas

### ISSUE THREAD

**Issue by roy350** [IIC2133-PUC/2018-1#19]
Tengo un problema con el free, resulta que si tengo dos listas y las concateno, mi primera lista quedara con los elementos de mi otra lista al final. Entonces tendre una lista1 con todos eso elementos y mi lista2, cuando hago free a la lista1 y luego a la lista2 me da error, por que mi destroy lo que hace es liberar cada nodo y luego liberar la lista misma, como libero la lista 1 se liberan ya los nodos de esta ya que quedan compartidos al concatenar, entonces como hago para liberar estas dos listas, por que me faltaria liberar el puntero de la lista2

**Comment by alopez7** [comment]
Hola, al concatenar A con B, B deberia desparecer y no deberías liberarlo

**Comment by roy350** [comment]
ahhhhh genial! :D muchas gracias por tu ayuda!

**Comment by roy350** [comment]
listo problema solucionado! muchas gracias :)

**Comment by roy350** [comment]
Otra duda sobre lo mismo, en los arreglos, al concatenar tambien se debe eliminar el segundo arreglo? para hacerlo de forma correcta :)

**Comment by alopez7** [comment]
Si
