### ISSUE TITLE
importar arraylist.c

### ISSUE THREAD

**Issue by gacuchac** [IIC2133-PUC/2018-1#20]
Para probar las funciones estoy usando el main, pero necesito importar arraylist.c, si no, tira el error de undefined reference to 'funcion'.

está bien?

**Comment by alopez7** [comment]
Como estás compilando?
Qué funcion estás llamando?
No deberías tener problema importanto el .h

**Comment by gacuchac** [comment]
el main que esta en la carpeta lista:
ArrayList *arraylist = arraylist_init();

**Comment by alopez7** [comment]
Cómo estas compilando?

**Comment by gacuchac** [comment]
make main y despues ./main

**Comment by gacuchac** [comment]
la terminal esta en la carpeta src/listas porque con no me funciono make solo en la carpeta programa

**Comment by alopez7** [comment]
Estás compilando mal
La makefile tiene que estar en un directorio junto con la carpeta src.
En ese directorio escribes make
Y luego ejecutas

**Comment by gacuchac** [comment]
listo, ya está, muchas gracias
