### ISSUE TITLE
Tiempos de funciones (Informe)

### ISSUE THREAD

**Issue by fvandeputte** [IIC2133-PUC/2018-1#21]
Hola! Tengo 3 preguntas:

1) En el informe sale que hay que analizar empiricamente las funciones. Significa que por ejemplo para la funcion append tengo que primerlo hacerlo con una sola estrucutra, hacer un make y luego ejecutarlo con time? (time ./listas). Luego hacer lo mismo con la otra y comparar? Y despues hacer lo mismo con 4, 8 , 16 datos por ejemplo?

2) En caso de ser asi, tendria un problema, por ejemplo para probar insert, concatenate se necesita usar la funcion append antes, luego los tiempos de esos programas "incluirian" los del append, por lo cual el analisis seria "sucio"

3) Al ejecutar time hay 3 tipos: user, real y sys. Que significan y cual hay que usar?

Gracias de antemano!

**Comment by alopez7** [comment]
Puedes usar la libreria time, funciona super bien. Tambien puedes usar time antes de tu programa.
Trata de provar con muchos datos: 1000, 2000, 3000,...

**Comment by alopez7** [comment]
O incluso con decenas de miles o sientoa de miles si es una operación rápida

**Comment by alopez7** [comment]
El tiempo de user es el que se demora en ejecucion de tu programa solamente.
El sys es el que se semora el sistema operativo en distintas operaciones que se realizan (cuando haces malloc, free, etc..)
El real es el tiempo real en segundos. Si no usas paralelismo entonces sys + user = real

**Comment by joseluishaddad** [comment]
hola @alopez7 , estoy usando difftime() de la librería time para calcular los tiempos de ejecución en segundo, pero me gustaría que me entregara decimales de los segundos o tener alguna función que me permita conocer milisegundos para saber los tpos con mayor exactitud. Algun consejo? o está bien que sea solo en segundos?

**Comment by nacosta-cl** [comment]
Usa clock: te indica cuantos ciclos de reloj tomo la operacion. Esta en <time.h>
`
clock_t t;
t = clock();
//cosas
t  = clock() - t;
printf ("Use %d ciclos (%f segundos).\n",t,((float)t)/CLOCKS_PER_SEC);
`
