### ISSUE TITLE
duda de insert

### ISSUE THREAD

**Issue by gacuchac** [IIC2133-PUC/2018-1#22]
tengo que revisar que la posicion dek insert sea menor que el size? si la posicion es mayor que count por ejemplo posicion es la ultima posicion del arreglo pero tengo solo la mitad del arreglo llenado, se agrega al final de los otros numeros, o en la posicion especificada?

[0,1,2,3,,,,,] y piden insert 4 en posicion 6, debe tirar error? quedar [0,1,2,3,,,4,,]? o [0,1,2,3,4,,,,]?

**Comment by alopez7** [comment]
No se debería poder insertar un dato al final del arreglo si eate no está lleno.
Todos los datos deben estar juntos en el comienzo del arreglo

**Comment by gacuchac** [comment]
la pregunta es si debemos retornar un error o ponerlo al final de la lista? el caso es que la posicion ingresada es incorrecta

**Comment by alopez7** [comment]
Ninguna de las dos opciones, no deben hacer nada. Puedes asumir que el usuario va a ser bueno y no va a hacer acciones ilegales

**Comment by haroldmuller** [comment]
Hola, respecto al insert, no me queda claro, si en el ejemplo que da gacuchac, me piden insertar en la posición 2, debo correr todos los datos desde la posicion 2 en adelante o solo reemplazar el valor en la posición 2. Muchas gracias :)

**Comment by asdegoyeneche** [comment]
@haroldmuller No se reemplaza, se deben correr todos los elementos desde la posicion a insertar en adelante
