### ISSUE TITLE
lista ligada

### ISSUE THREAD

**Issue by gacuchac** [IIC2133-PUC/2018-1#23]
Puedo agregarle a la lista ligada el puntero de la última dirección?
struct { int valor; int *siguiente; int *ultimo;}
es para que no tenga que recorrer todo en append

**Comment by gacuchac** [comment]
Cuando inicializo el linkedlist le doy valor 0, entonces el primer nodo es 0 excepto que lo cambie a proposito hay algun problema?

**Comment by DiegoAndai** [comment]
Sobre la primera pregunta: #5

**Comment by alopez7** [comment]
En general se usa una estructura linked list y otra estructura Node:
LinkedList: tiene referencia al primer y al ultimo nodo y la cantidad de nodos
Nodo: tiene un int y una referencia al nodo siguiente.

**Comment by alopez7** [comment]
Tu solución de apuntar al ultimo nodo es válida. También puedes hacer que cada nodo apunte al nodo siguiente y al anterior y hacer que sea circular la lista (el ultimo tiene referencial al primero y el primero al ultimo)

**Comment by gacuchac** [comment]
Lo deje como un struct que tiene un int que es el valor y un puntero a otro linked list. El primero por default tiene valor 0 y el último apunta a nada.

**Comment by alopez7** [comment]
En este caso vas a tener problemas para encontrar eficientemente el final de la lista
