### ISSUE TITLE
Error al ejecutar archivo

### ISSUE THREAD

**Issue by Dalal15** [IIC2133-PUC/2018-1#26]
Hola!

Terminé mis estructuras y al momento de probarlas no puedo ejecutar el archivo main.c. Primero compila bien, pero luego al ejecutar el archivo me aparece "Permiso denegado".

¿Cómo puedo solucionar esto?

Gracias!

**Comment by gbordoni** [comment]
Aprovecho de colgarme de la pregunta, a mi cuando trato de guardar los cambios que voy haciendo
en los archivos .c y .h simplemente no me deja y me sale "Unable to save file: Permission Denied"

**Comment by nacosta-cl** [comment]
Si es linux, haganle un chmod 777 y vean que pasa :D

**Comment by alopez7** [comment]
Tienen que ejecutarlo como ./programa

**Comment by Ghoeb** [comment]
@gbordoni eso depende totalmente de en que carpeta estás. tienes que trabajar bajo "home"

**Comment by Dalal15** [comment]
Muchas gracias, ya lo arreglé!
