### ISSUE TITLE
Concatenate LinkedList

### ISSUE THREAD

**Issue by ManuelBeckerT** [IIC2133-PUC/2018-1#27]
Si es que tengo 2 listas, lista1 fue instanciada (sólo init) y lista2 se le agregan elementos. Al hacer concatenate de lista1 con lista2 debiese quedar solamente lista1 con todos los elementos de lista2? O al hacer concatenate de una lista que solo fue instanciada no se pueden unir ambas? 
Qué debiese quedar al final como resultado de esa operación?

**Comment by alopez7** [comment]
En ese caso queda la lista con todos los datos
