### ISSUE TITLE
error valgrind

### ISSUE THREAD

**Issue by roy350** [IIC2133-PUC/2018-1#28]
valgrind me dio unos errores, pero no entiendo muy bien, se supone que si estoy liberando la memoria de estos nodos pero creo que no esta ocurriendo eso, cualquier cosa mi codigo esta subido en mi repo
<img width="891" alt="captura de pantalla 2018-03-16 a la s 20 28 20" src="https://user-images.githubusercontent.com/20785160/37549225-b986668a-295c-11e8-9f8d-fdef36fab1fb.png">

**Comment by Ghoeb** [comment]
Lo que se muestra es el stack de llamadas, por lo que aparece en el orden inverso. 

Básicamente, en la línea `39` del archivo `main.c`, llamaste a la función `linkedlist_insert`. Dentro de esa función, en la línea `69` del archivo `linkedlist.c`, llamaste a la función `node_init`. Dentro de esa función, en la línea `16`, llamaste a `malloc`. Ese _malloc_ es precisamente el que no estás liberando.
