### ISSUE TITLE
Implicit Declaration

### ISSUE THREAD

**Issue by PabloAbara** [IIC2133-PUC/2018-1#3]
Hola! 

El programa me advierte sobre una "implicit declaration" de una función no declarada en el archivo con extensión ".h". Cómo se discrimina sobre cuáles deben ser declaradas y cuáles no? 

Gracias,

**Comment by Ghoeb** [comment]
Te dice "implicit declaration" cuando llamas una función que no has declarado previamente. ¿Qué función es, y en que archivo estás?

**Comment by PabloAbara** [comment]
Estoy declarando una función para "duplicar el tamaño del arreglo" en el archivo "arraylist.c" sin haberlo declarado en el "arraylist.h". En el fondo, dicha función será una consecuencia de agregar un elemento, no se debería llamar directamente, o no?

**Comment by alopez7** [comment]
Puedes no agregarlo al archivo .h si no lo llamas desde afuera.
También te puede tirar ese error si defines esa función más abajo en el código de donde la llamas.
Las funciones que estén solo en el .c se definen al principio.

**Comment by PabloAbara** [comment]
Ahh perfecto. Me tiraba warning porque no estaba en el .h y además porque estaba abajo jajaja 
Gracias!

**Comment by Ghoeb** [comment]
@PabloAbara Si, eso es importante en C, solo puedes llamar a una función que esté declarada arriba.
