### ISSUE TITLE
Que archivo ejecutar

### ISSUE THREAD

**Issue by gbordoni** [IIC2133-PUC/2018-1#33]
Hay que ejecutar el main.c o el main.o que se crea en obj? Logre compilar pero cuando intento hacer ./main.c me aparece "bash: ./main.c: Permission denied" y no logro resolverlo.

saludos

**Comment by Ghoeb** [comment]
Make compila tu programa entero, a un ejecutable llamado "listas" (creo que se llama así), para ejecutarlo usas `./listas`

**Comment by gbordoni** [comment]
Muchas gracias!
