### ISSUE TITLE
Libros guía

### ISSUE THREAD

**Issue by berrazuriz1** [IIC2133-PUC/2018-1#34]
En la ayudantia pasada mencionaron un libro para estudiar ¿cual era?
Gracias

**Comment by haroldmuller** [comment]
cormen, aqui está el [link](http://ressources.unisciel.fr/algoprog/s00aaroot/aa00module1/res/%5BCormen-AL2011%5DIntroduction_To_Algorithms-A3.pdf)

**Comment by Ghoeb** [comment]
Venia a lo mismo :) 

El otro es el Sedgewick, está [aquí](http://www.albertstam.com/Algorithms.pdf)
