### ISSUE TITLE
Duda I1 2016-2

### ISSUE THREAD

**Issue by roy350** [IIC2133-PUC/2018-1#36]
Hola! me surgió una duda en la pregunta 3b del árbol AVL, al principio de la ultima linea en la pauta hacen una rotación, pero la diferencia entre los nodos derechos e izquierdos es 1, según lo que yo tenía entendido si la diferencia es 0 o 1 el árbol esta balanceado y no se necesita rotar, quizás estoy confundido, por eso pregunto en caso que este equivocado, muchas gracias de antemano :D
<img width="1022" alt="captura de pantalla 2018-03-30 a la s 01 40 19" src="https://user-images.githubusercontent.com/20785160/38124864-80fc4b18-33bb-11e8-87e0-256d9ddccea1.png">

**Comment by alopez7** [comment]
En laa ultima linea se hacen 2 rotaciones. En la primera el nodo L está desbalancedado (tiene un hijo de altura 0 y otro de altura 2). En la segunda roración el caso es el mismo pero en el nodo P

**Comment by roy350** [comment]
ya entendi! muchas gracias!
