### ISSUE TITLE
Interfaz Gráfica T1

### ISSUE THREAD

**Issue by Ghoeb** [IIC2133-PUC/2018-1#37]
Para poder usar la interfaz gráfica de la T1, deben instalar la librería correspondiente en su computador. Pueden encontrar las instrucciones [aquí](https://github.com/IIC2133-PUC/2018-1/wiki/4.-Setup-GTK--3)

Recuerden probar los ejemplos que están en el repositorio, en la carpeta `Ejemplos/GTK`

**Comment by sebawarrior** [comment]
hola, estoy teniendo problemas con la instalación de GTK, tengo los siguientes archivos:
  - The GLib, Pango, GdkPixbuf, ATK and cairo libraries, available at
   the same location as GTK+. GTK+ 3.2.0 requires at least
   GLib 2.29.14, Pango 1.29.0,
   GdkPixbuf 2.23.5, ATK 2.1.5
   and cairo 1.10.0.

 - gobject-introspection 0.10.1 or newer.

![image](https://user-images.githubusercontent.com/13771365/38581205-835b0086-3ce2-11e8-92eb-38c49a74f90c.png)

y aplico los comandos:

Simple install procedure
========================

  % cd gtk+-3.2.0                          # change to the toplevel directory
  % ./configure                                    # run the `configure' script
  % make                                           # build GTK+
  [ Become root if necessary ]
  % make install                                   # install GTK+

Y aun sí me tira error. Podrías darme alguna ayuda de cómo instalarlo correctamente, o si estoy haciendo algo mal? muchas gracias.

**Comment by sebawarrior** [comment]
no me funciono con el comando original, y lo hice a mano, por eso no entiendo si estoy haciendo algo mal (lo que hice es lo que sale en la foto y los pasos que dice despues)

**Comment by Ghoeb** [comment]
Ok, pero que error es el aparece cuando ejecutas el comando original?

**Comment by sebawarrior** [comment]
No me tira error pero no ejecuta nada... y el gtk no es reconocido al compilarlo...
![image](https://user-images.githubusercontent.com/13771365/38583109-5bc1709a-3ce8-11e8-8df6-1846a8b9f8cc.png)

**Comment by Ghoeb** [comment]
Uf. Te voy a pedir que ejecutes el siguiente comando:

```
pkg-config --cflags --libs gtk+-3.0
```

**Comment by sebawarrior** [comment]
Me aparece esto:
![image](https://user-images.githubusercontent.com/13771365/38594651-b46c2f70-3d1d-11e8-8f98-83c2a7337b6a.png)
Gracias!!

**Comment by Ghoeb** [comment]
Eso se ve bien... Dices que está fallando la compilación del código base? Probaste con los ejemplos?

**Comment by sebawarrior** [comment]
Al compilarlo, me dice que gcc no existe

**Comment by Ghoeb** [comment]
Em, gcc es el compilador de C, asique esto no es un problema de gtk. ¿Cómo probaste el código de la actividad 0? 

Y bueno... Probaste que pasa si **instalas** gcc...?

**Comment by Ghoeb** [comment]
Y bueno ademas esta el hecho de que gcc viene con ubuntu, asique de alguna u otra manera te las arreglaste para borrarlo...?

**Comment by sebawarrior** [comment]
gcc me funciona! de hecho he podido compilar todos mis programas de c... nosé si me puedes ayudar quizás después de la clase de hoy, porque en serio no sé como solucionarlo jaja

**Comment by Ghoeb** [comment]
Rarísimo. Ok, veamoslo despues de la clase de hoy.

**Comment by sebawarrior** [comment]
Muchísimas gracias!!

**Comment by Zepk** [comment]
Y como solucionaron el problema? Me pasa lo mismo a mi

**Comment by Ghoeb** [comment]
Resulta que estaba compilando con gcc sin incluir los flags de gtk, en lugar de usar make

**Comment by vjmoreno** [comment]
@Ghoeb luego de instalar la libreria, al intentar probar con los ejemplos me sale el siguiente error:
```
fatal error: gtk/gtk.h: No existe el archivo o el directorio
compilation terminated.
```

**Comment by Ghoeb** [comment]
@vjmoreno ¿Cómo estas haciendo para compilar?

**Comment by vjmoreno** [comment]
Utilizo el package Script

**Comment by Ghoeb** [comment]
¿No usas make? ¿Eso que está explicado en la guía de C y que explicamos en la ayudantía?

**Comment by vjmoreno** [comment]
No porque no me funcionó para la actividad pasada y Script si me funcionó

**Comment by alopez7** [comment]
Que outout en consola da cuando compilas con make?

**Comment by vjmoreno** [comment]
`done compiling`
Pero después cuando intento ejecutar mis programas me sale acceso denegado. Como se debe escribir la segunda instrucción?

**Comment by alopez7** [comment]
Debes llamar a tu programa con ./ antes

**Comment by vjmoreno** [comment]
Se supone que se me deben generar archivos ejecutables? Porque no se me genera nada

**Comment by Ghoeb** [comment]
@vjmoreno que pasa cuando ejecutas `ls` luego de hacer make?

**Comment by vjmoreno** [comment]
acabo de notar que se me genera un archivo llamado listas y una carpeta llamada obj, la cual contiene archivos .o En que carpetas deben estar los archivos que deseo compilar? dentro de la carpeta src? o da lo mismo?

**Comment by Ghoeb** [comment]
> Se supone que se me deben generar archivos ejecutables? Porque no se me genera nada

El archivo `listas` es un ejecutable. 

Los archivos a compilar deben estar dentro de src, en alguna de las carpetas que les pasamos: la Makefile viene configurada para compilar lo que hay en esas carpetas.

Para el caso de la T1, la idea es que modifiques solo el código dentro de la carpeta src/filter, ya que las demás las cambiaremos para la corrección.

**Comment by vjmoreno** [comment]
@Ghoeb o @alopez7 , alguno de ustedes tiene un tiempo libre mañana en el que me puedan ayudar con la  interfaz? lo he intentado todo y no me funciona

**Comment by alopez7** [comment]
Yo no voy a la U mañana, y vicho tampoco.
