### ISSUE TITLE
Demostración de complejidad

### ISSUE THREAD

**Issue by PabloAbara** [IIC2133-PUC/2018-1#38]
Hola, quería saber si podemos demostrar "O de algo" utilizando cosas como el algoritmo de "Sustitución", "Árboles de recurrencias" o "Master Method" del Cormen... sobre todo el último, ya que no lo hemos demostrado en clases pero a veces se aplica directamente. 
¿Es legal? O tenemos que hacerlo por "inspección" matemática para llegar a la complejidad de forma precisa? 

Salu2

**Comment by alopez7** [comment]
Si tu demostración es correcta no importa el método. Es raro que tengas que usar algún método especial para demostrar, ya que en general se piden demostraciones que se pueden hacer mas fácil que usando el teorema maestro por ejemplo.

**Comment by Ghoeb** [comment]
Ojo que igual nos interesa ver que entiendes de donde sale y poder hacer el razonamiento: no tiene gracia que se aprendan fórmulas del teorema maestro para calcular complejidades si es que no lo entienden.
