### ISSUE TITLE
Dudas T1

### ISSUE THREAD

**Issue by Diiru** [IIC2133-PUC/2018-1#39]
Hola,
Ya descargué GTK y pude visualizar los "circulos", estatico y dinámico.

Tengo un par de dudas,

1) Sólo debemos programar en filter/main.c, cambiando los "Pasos" que hay actualmente ?
O también tenemos que cambiar las estructuras de Linked List y Point ?

2) El programa inicialmente entregado debería compilar con "./filter mosque.png 22 33", cierto ?
Hago esto y me sale Segmentation fault,

<img width="582" alt="screen shot 2018-03-31 at 22 29 21" src="https://user-images.githubusercontent.com/13814193/38168968-fd0ba046-3532-11e8-97c2-ea0dd392c733.png">

Qué tengo que hacer/cambiar ?

3) Sobre las opciones que tenemos que analizar; al usar distintos criterios para el termino de una caja KdTree y las variantes al uso de la mediana como división, tenemos que dejarlas en el código (comentadas) o solo mencionamos su uso/resultados en el informe ?

Muchas gracias de antemano !

**Comment by alopez7** [comment]
1. Cambia lo que estimes necesario (main, listas, etc..) pero solo dentro se la carpeta src/filter.
2. Debes escribir la ruta y nombre completo de la imagen, por ejemplo imgs/mosque.png.
3. Debes entregar la que funcione mas rápido posible, ya que el corregir el código se juzgará según la eficiencia.

**Comment by berrazuriz1** [comment]
¿Por que nos dieron una estructura de linkedlist, siendo que lo que necesitamos, yo creo, es un arbol binario? Como que no me hace sentido que hayan subido algo que tenemos que cambiar, la otra opcion sería que yo este muy perdido.

**Comment by alopez7** [comment]
Estás un poco perdido, esa linked list se usa solo para guardar los pixeles que corresponden a un núcleo. A priori antes de buscar no se sabe cuantos pixeles son. Es por eso que una lista es adecuada.

**Comment by berrazuriz1** [comment]
Si, ayer como dos minutos despues de preguntar me di cuenta que estaba perdido.
