### ISSUE TITLE
Consulta Concatenación

### ISSUE THREAD

**Issue by sgvasquez** [IIC2133-PUC/2018-1#4]
Hola! Al concatenar A con B debemos crear una nueva estructa que contenga secuencialmente A y B, o solo agrandamos la memoria de A y ponemos los elementos ahí?

De la misma forma, que pasa con B? Se elimina? Queda sin cambios?

Saludos!

**Comment by asdegoyeneche** [comment]
Hola!
Se debe agregar la lista B a la lista A (agrandando la memoria de A si es necesario). La lista B queda intacta.
Saludos!

**Comment by sgvasquez** [comment]
Gracias!

**Comment by MortizDX** [comment]
Cuando se une una lista A a la otra B, la idea es que sea una "copia" de B o la misma lista B? Lo pregunto porque si solo "conecto" las listas entre sí, al liberar memoría de A y luego intentar liberar la de B, me tira avisos la consola, puesto que ya debí liberar los nodos de B al borrar la lista A.

**Comment by Ghoeb** [comment]
Buen punto... La idea es que no hagas una copia, la lista B pasa a ser parte de la lista A. (Y puedes olvidarte de la lista B)

**Comment by MortizDX** [comment]
Al evaluar no se preocuparan de esos errores entonces? (tratar de liberar algo que ya fue liberado quiero decir)

**Comment by matnagra** [comment]
Yo implemente que se hiciera una copia de los nodos de B y se fueran ligando a la lista A, ya que pensé que la idea era que si se liberaba el espacio de la lista B no debía afectar a la lista A.
¿Debo cambiarlo?

**Comment by Ghoeb** [comment]
@MortizDX Oh, eso hace que se te caiga el programa. Por supuesto que debes manejar la memoria, pero puedes vaciar la lista B luego de hacerle una concatenación.

@matnagra La idea de esta operación es que en listas ligadas es O(1), mientras que en arreglos es necesario copiar elemento por elemento. Así que si, deberías cambiarlo.

**Comment by MortizDX** [comment]
Entonces, cuando concateno una lista B a una otra lista A, ¿elimino la referencia a la lista B original? Para que no quede espacio sin liberar después (aunque tratar de liberar memoria no detiene la ejecución de mi código al parecer).

**Comment by Ghoeb** [comment]
@MortizDX Exacto

**Comment by diflores** [comment]
¡Hola! 
Solo para confirmar: al concatenar una lista `list1` con otra llamada `list2`, ¿debo liberar la memoria asignada a `list2`?. Pregunto porque más arriba dice que la segunda lista debe quedar intacta y siguiendo esa instrucción y luego liberando `list1`y `list2`, Valgrind me lanza un error (no se interrumpe la ejecución, eso sí) por intentar liberar memoria que ya está libre.

¡Gracias de antemano!

**Comment by Ghoeb** [comment]
@diflores Lo de que la lista2 queda intacta fue un malentendido. Basicamente luego de hacer concatenación lo unico que te importa es la lista grande que ahora tiene los datos de ambas listas. Puedes olvidarte (y liberar la memoria) de la lista que quedó sola.

**Comment by diflores** [comment]
@Ghoeb ¡Gracias por la rápida respuesta!
