### ISSUE TITLE
Acerca de convertir un arreglo en un Heap

### ISSUE THREAD

**Issue by Ghoeb** [IIC2133-PUC/2018-1#40]
Hacer bajar los nodos que están en el penúltimo piso cuesta 1. Para el piso de arriba cuesta 2, pero son la mitad de nodos. Para el de arriba cuesta 3, pero son la mitad de nodos. En general, para un nodo que esta en el piso x de abajo hacia arriba, es necesario realizar x operaciones en el peor caso. Solo la raíz cuesta x = log(n), y es un solo nodo.

Si son n nodos, n/2 son el piso de abajo.

Asique en total convertir el arreglo en un heap es:

![image](https://user-images.githubusercontent.com/5317897/38214283-8f0ff8d0-369a-11e8-9d7e-9ec0a066c4e2.png)

Eso es:

![image](https://user-images.githubusercontent.com/5317897/38214171-2f36aa62-369a-11e8-95ab-66c7d77c3ac4.png)

Y eso es:

![image](https://user-images.githubusercontent.com/5317897/38214194-4355b114-369a-11e8-9c75-7e6e75021e05.png)

[Discúlpenme, markdown no es lo más apropiado para poner fórmulas matemáticas]

Resolviendo esa sumatoria podemos llegar a que finalmente el costo es

n - O(logn)

Lo cual es O(n).

**Comment by jorgeriesco** [comment]
Esto es un arreglo desordenado convertirlo en heap? No entiendo muy bien a que te refieres con bajar, porque yo me imagino armar el árbol con puros inserts uno por uno del arreglo y con eso el peor caso sería que justo el arreglo está al reves y se harían muchos intercambios. No se si estoy bien, por lo que parece no. Alguna ayuda?

**Comment by gacuchac** [comment]
Pero un heap no es más que una representación de arreglo en el que el nodo i tiene como hijos a los nodos 2i y 2i+1 Si lo vemos así, todo arreglo es un heap y lo que necesitamos es ordenarlo o extraer e insertar datos. No se a qué se refieren con pasar un arreglo a un heap. Tengo un error conceptual?

**Comment by jorgeriesco** [comment]
Pero no todo arreglo es un heap. La idea del heap es que los hijos sean menores al padre. Luego de formar el heap puedes ponerlo como árbol o arreglo, pero no al revés directamente.

**Comment by alopez7** [comment]
El heap se puede hacer implícitamente en un arreglo. Con bajar se refiere a que se mueve hacia abajo en el heap (si es necesario)

**Comment by Ghoeb** [comment]
@jorgeriesco @gacuchac  eso es lo que se hace al empezar heapsort: se construye el heap con los elementos que queremos ordenar. La gracia es que los ultimos n/2 elementos corresponden al último piso de lo que sería el heap, por lo que se dice que inicialmente están "listos". De ahi se va subiendo por cada piso haciendo bajar los elementos que no cumplen las propiedades del heap. Como un heap se puede representar como un arreglo, hacemos eso: y usamos el mismo arreglo en el que vienen los datos.

**Comment by jorgeriesco** [comment]
gracias!

**Comment by gacuchac** [comment]
Gracias
