### ISSUE TITLE
Insertion Sort (ambigüedad)

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2133-PUC/2018-1#41]
Hay algo que no me queda claro de Insertion sort:

Supongamos que quiero ordenar de menor a mayor y tengo una lista A totalmente al revés y una B vacía.
Al sacar cada primer elemento de A e insertarlo en B donde corresponda, ¿parto comparando desde el principio de B o desde el final?
Dependiendo de como sea, si es desde el principio, entonces haré n comparaciones, pero si es desde el final haré 1 + 2 + 3 +...+n comparaciones.
Teniendo eso en cuenta, mi mejor caso, de la primera forma, sería que me pasaran el arreglo al revés y el peor que estuviera ordenado. De la segunda forma sería lo contrario.

¿Como sería entonces?

**Comment by alopez7** [comment]
Partes de atras pa adelante
