### ISSUE TITLE
Tiempos Tests

### ISSUE THREAD

**Issue by yoavnavon** [IIC2133-PUC/2018-1#43]
Hola! Hay alguna posibilidad de que nos digan más o menos cuales serían los inputs y los tiempos esperados para la tarea. Esto para saber si mi programa funciona aproximadamente como lo esperado, o debo optimizarlo aún mas. Saludos!

**Comment by alopez7** [comment]
Hola, se darán test pronto, pero lamentablemente el tiempo del programa depende mucho del computador donde se ejecute el programa, por lo que no te servirá un tiempo de referencia.

**Comment by yoavnavon** [comment]
Se me ocurre que quizás podrían decirnos cuanto demora el programa base que era O(n^2) en el computador de los test, eso nos daría una idea de las diferencias. De todas maneras gracias!!

**Comment by alopez7** [comment]
La implementacion del codigo base se demora O(pixeles*nucleos).
Se espera que la suya sea O(pixeles*log(nucleos))

**Comment by PabloAbara** [comment]
Y el overhead de armar el árbol? Cuántos núcleos son "hartos" en ese sentido?

**Comment by alopez7** [comment]
Si haces el árbol con mediana en O(n) deberías poder construir el árbol en O(núcleos * pisos). Y los pisos deberían ser proporcionales al logaritmo de los núcleos, por lo que la construcción debería ser O(núcleos x log(núcleos))

**Comment by PabloAbara** [comment]
Con "Si haces el árbol con mediana en O(n)" te refieres a la búsqueda de la mediana? Osea, me demoro O(n) en encontrar la mediana de un set de datos, por lo que debería hacer O(n)*nucleos*log(nucleos) o no?

**Comment by alopez7** [comment]
Si, el algoritmo de mediana visto en clases (quickselect) se demora O(n) en promedio. (OJO: se demora O(n) en promedio, pero en el peor caso se demora O(n x n)
