### ISSUE TITLE
Tip útil para la tarea.

### ISSUE THREAD

**Issue by alopez7** [IIC2133-PUC/2018-1#44]
Hola, para la tarea es probable que usen el algoritmo quickselect visto en clases para encontrar la mediana en un grupo de datos. Les quiero recordar que el peor caso de este algoritmo es O(n^2), y se da cuando los datos están muy ordenados. Les comento esto porque es muy probable que se de este peor caso ya que al buscar la mediana muchas veces los datos se tienden a ordenar (ya que se esta haciendo partition muchas veces). Para evitar esto les recomiendo elegir el pivote para partition de alguna manera mas inteligente que solo tomar el primer dato. Esto puede ser tomar el de la mitad; tomar uno random; tomar el primero, el de al medio y el ultimo y usar la mediana de los 3; etc...

**Comment by gacuchac** [comment]
pero puedo usar quicksort para ordenarlos y tomar siempre la mediana de los sub arreglos y como el peor caso de quicksort es O(n²) pero es mucho más raro que el peor de quickselect, en promedio debería ser más rápido, porque el quicksort lo hago una sola vez y la mediana se elige en O(1) A[largo/2]

**Comment by gacuchac** [comment]
muchas gracias
