### ISSUE TITLE
Repo de la tarea

### ISSUE THREAD

**Issue by jgramsch** [IIC2133-PUC/2018-1#46]
Hola!, cuando van a entregar los repos de la tarea 1? aún no me llegan notificaciones de eso.

Saludos

**Comment by Ghoeb** [comment]
Los repos fueron entregados el día 1. Buscaste el tuyo [aquí](https://github.com/IIC2133-PUC) ?

**Comment by gacuchac** [comment]
A mi me aparece solo el de la actividad 0 y el del curso (este y semestres pasados)

**Comment by Ghoeb** [comment]
Curioso...
@gacuchac https://github.com/IIC2133-PUC/gacuchac-T1-IIC2133-PUC-2018-1
@jgramsch https://github.com/IIC2133-PUC/jgramsch-T1-IIC2133-PUC-2018-1

**Comment by gacuchac** [comment]
Muchas gracias, no me aparecía

**Comment by jgramsch** [comment]
Vale gracias, a mí tampoco !

**Comment by berrazuriz1** [comment]
A mi tampoco me aparece!

**Comment by alopez7** [comment]
Métanse a:
https://github.com/IIC2133-PUC/suusuariodegithub-T1-IIC2133-PUC-2018-1
