### ISSUE TITLE
Seed y Números Enteros

### ISSUE THREAD

**Issue by PabloAbara** [IIC2133-PUC/2018-1#47]
Hola! Tengo un par de dudas: 
Primero: Podemos asumir posiciones enteras para los núcleos, verdad? Sino puede llevar a problemos :S 
Segundo: No estoy entendiendo lo de la  "seed" como parámetro? Es un int nomás? Muy rookie pedir ayuda por acá? 

Gracias!!

**Comment by Ghoeb** [comment]
1) No pueden asumir posiciones enteras para los núcleos: por eso son doubles.

2) La seed es un numero entero positivo. La gracia es que determina por completo los números aleatorios que saldrán en tu programa: asi a la hora de corregir todos van a trabajar con el mismo set de núcleos.

**Comment by sebawarrior** [comment]
Pero si los nucleos en teoria son puntos a partir de los cuales veo la minima distancia entre los pixeles, como es eso de que sean double??

Y la seed qué determina?? No entiendo tampoco el rol que juega la seed. Muchas gracias!

**Comment by Ghoeb** [comment]
Double significa que no son numeros enteros, por lo tanto no corresponden a pixeles de la imagen

Lo puse en el comentario anterior: la seed determina la secuencia de números aleatorios que genera el generador de números aleatorios. Así, si bien los núcleos son aleatorios, puedes probar tu programa con los mismos núcleos mientras uses los mismos parámetros.

**Comment by gacuchac** [comment]
Si no corresponden al pixel i,j a qué corresponden?

**Comment by Ghoeb** [comment]
A un punto **entre** pixeles

**Comment by sebawarrior** [comment]
Y para términos de la tarea, los pixeles de la imagen original, sus coordenandas SÍ son enteras cierto? y los núcleos son los que pueden estar en "cualquier" posición dentro de la imagen?

**Comment by gacuchac** [comment]
La cantidad de núcleos es un entero, pero si un núcleo se encuentra en la posición 5,1234;9,678 significa que está entre 5,9 6,9 5,10 y 6,10? Para eso podría usar un entero donde el nucleo i,j se encuentra entre los pixeles i,j i,j+1 i+1,j e i+1,j+1

**Comment by Ghoeb** [comment]
@sebawarrior N es el número de nucleos, por ejemplo, 10.

Eso significa que para cada núcleo se generan dos números aleatorios dentro de la imagen, uno para su X, y otro para su Y.

Un ejemplo de núcleo sería
X = 12.3829, Y = 56.1827

@sebawarrior Exacto

@gacuchac Si, eso significa. Para que quieres hacer eso? Digo, despues de todo para calcular la distancia viene una función que se encarga de eso... pretendes acelerar la búsqueda sin usar un KD-Tree? Debes asegurar 100% que el resultado sea el mismo que sin la optimización...

**Comment by gacuchac** [comment]
quería asegurarme que estaba entiendo la tarea y solo que es mucho más costoso calcular la distancia de doubles que de ints tanto en memoria como en tiempo.

**Comment by Ghoeb** [comment]
@gacuchac Creeme que te va a ser más costoso calcular la distancia a 4 puntos distintos con coordenadas enteras que a un solo punto con coordenadas reales.

Además, ese costo es totalmente negligible frente a la complejidad del problema: creeme que la diferencia de tiempo de trabajar con ints vs doubles no es suficiente como para que se note.

Preocupate del algoritmo y de que funcione bien, esas micro-optimizaciones no van a hacer más que complicarte la vida.

**Comment by sebawarrior** [comment]
Yaa perfecto, entonces en el input, N es la cantidad (entera de nucleos) y la seed sera la base para calcular las posiciones aleatorias (doubles) en las que se encontrarán mis N núcleos. Por último, para entender por completo el enunciado, la semilla debe constar de dos enteros? (digo, para generar números aleatorios en x y otro para y)? Eso, en verdad gracias y perdona lo pregunton jajaja

**Comment by Ghoeb** [comment]
@sebawarrior No, la semilla es un solo número, el generador va generando x e y por turnos.

**Comment by sebawarrior** [comment]
Eso asume que la foto es cuadrada, porque o sino, los generadores debieran ser distintos cierto?

**Comment by jpdattas** [comment]
Hola. Se puede asumir que no hay 2 nucleos en la misma posicion?
