### ISSUE TITLE
Ayuda T1 y estadísticas de la solución

### ISSUE THREAD

**Issue by alopez7** [IIC2133-PUC/2018-1#48]
Hola, si están complicados con la colisión de circulo con bouning box, les dejo un link que lo explica muy bien: https://yal.cc/rectangle-circle-intersection-test/

Mi implementacion es la siguiente:
```c
bool aabbcc(double minx, double miny, double maxx, double maxy, int row, int col, double radius)
{
  double delta_x = col - max(minx, min(col, maxx));
  double delta_y = row - max(miny, min(row, maxy));
  return (delta_x * delta_x + delta_y * delta_y) < (radius * radius);
}
```

El output de su programa debe ser la imagen final de la ventana, y su programa debe terminar en menos de 10 segundos. Esto significa que no deben poner sleeps en su programa porque podría dar timeouts. Tampoco les convine dibujar la imagen original en la ventana ya que consume mucho tiempo.

Les dejo también una estadística de mi solución para que comparen. Lo que medí es el número de llamadas a la función euclidean_distance. Mi implementación es muy básica, por lo que su programa debería tener un número de llamadas a la función menor o igual a la mía.

| imagen | nucleos | seed | llamadas |
|:--------:|:---------:|:------:|:----------:|
| lena | 10.000 | 1 | 8.660.329 |
| lena | 50.000 | 1 | 9.943.989 |
| lena | 250.000 | 1 | 11.300.395 |
| mosque | 10.000 | 1 | 11.892.701 |
| mosque | 50.000 | 1 | 13.643.498 |
| mosque | 250.000 | 1 | 15.484.371 |
| rose | 10.000 | 1 | 13.522.797 |
| rose | 50.000 | 1 | 15.514.965 |
| rose | 250.000 | 1 | 17.594.981 |

Si quieren contar sus llamadas a la funcion euclidean_distance pueden crear una variable global en el archivo point.h sin inicializar: 
```c
int times_called;
```
Luego en el archivo main.c inicializan esa variable en 0:
```c
times_called = 0;
```
Finalmente en el archivo point.c editan la función euclidean_distance y la dejan así:
```c
double euclidean_distance(Point a, double row, double col)
{
	times_called++;
	return sqrt(pow(a.X - col,2) + pow(a.Y - row, 2));
}
```

**Comment by alainrochette** [comment]
10 segundos es el tiempo total del programa incluyendo la construcción del árbol?

**Comment by gacuchac** [comment]
10 segundos es usando valgrind? Y en que máquina? Mi laptop es viejo y sin valgrind igual termina antes que 10 segundos, pero cuando ejecuto valgrind con muchos nodos se demora una infinidad

**Comment by Ghoeb** [comment]
@gacuchac Valgrind ralentiza **mucho** los programas, por lo que los limites de tiempo que pongamos siempre serán sin valgrind.

Independiente de la máquina en la que estén, la cantidad de llamadas a `euclidean_distance` es una buena métrica de cuanto demora la parte de búsqueda de tu programa. Si en tu computador se demora menos de 10 segundos, pero tienes ordenes de magnitud más llamadas a la función, entonces tu programa esta en la complejidad equivocada.

**Comment by gacuchac** [comment]
de que tamaño son las imagenes que probaste?

**Comment by alopez7** [comment]
Con las imagenes que estaban en sus repos en la carpeta Programa/imgs.
Como dije antes el tiempo es relativo al computador.

**Comment by fcgfaura** [comment]
...

**Comment by alopez7** [comment]
Cada vez que necesito saber si un nucleo está mas cerca de mi pixel en ese momento. Cuando llego a las hojas buscanfo.

**Comment by dalliende** [comment]
Se medira la eficiencia solo con las llamadas a distancia?,  o si ocupamos comandos como el para ver colisiones aabbcc o similares tambien se consideraran?

**Comment by alopez7** [comment]
Se correrá tu código con un tiempo limite

**Comment by alopez7** [comment]
No! Los sleeps hacen que tu programa de timeout. Tampoco ningun getchar().

**Comment by dalliende** [comment]
hola, no entendi, se evaluara el tiempo que toma mostrando la imagen? o podemos entregar nuestro codigo en el cual solo se edita la imagen pero no se muestra?. Y los segundo, se entrega sin el sleep entonces?. Saludos

**Comment by Ghoeb** [comment]
@dalliende 

De la sección "Output" del enunciado:

> El output de tu programa debe ser la imagen filtrada mostrada en la interfaz gráfica que se te provee.

De la sección "Evaluación" del enunciado:

> Tu programa deberá ser capaz de obtener el output de los tests dentro de un tiempo acorde a la complejidad esperada. Pasado ese tiempo el programa será terminado y se asignarán 0 puntos en ese test.

Ponle los sleeps que quieras, pero si se pasa del tiempo límite tendrás 0 puntos. Lo dejo a tu criterio.

**Comment by Ghoeb** [comment]
Lo que se va a medir es el tiempo que toma tu programa desde que **empieza** hasta que **termina**, si esa es tu duda.

**Comment by berrazuriz1** [comment]
El problema con eso es que mi computador ya es malo, ademas estoy ocupando una maquina virtual, por lo que tengo la mitad de la capacidad, pero la cantidad de veces que llamo a euclidean_distance es siempre menor, ¿me puedo quedar tranquilo?

**Comment by berrazuriz1** [comment]
Pero se demora mucho más, con 10.000 nucleos ya se demora como un minuto.
