### ISSUE TITLE
Duda listas ligadas

### ISSUE THREAD

**Issue by roy350** [IIC2133-PUC/2018-1#5]
Hola! en la actividad de listas ligadas, podemos agregar una struct aparte de la de lista ligadas, como una struct nodo?

**Comment by alopez7** [comment]
Si, es lo ideal. Puedes hacer la struct en el archivo linkedlist.h

**Comment by roy350** [comment]
muchas gracias!

**Comment by jgramsch** [comment]
Se puede hacer solo definiendo la estructura principal como un nodo y agregando structs LinkedList a las colas?

**Comment by nivek0o0** [comment]
@Ghoeb Y si la lista estuviese compuesta de nodos, suponiendo que tengo un puntero al primero ¿ no habría que recorrerlos uno por uno de todas formas para acceder al último?

**Comment by Ghoeb** [comment]
@nivek0o0 Puedes mantener constantemente una referencia al último nodo, lo cual te ocupa O(1) en memoria y hace que la inserción sea O(1). Por qué no lo harías?

**Comment by nivek0o0** [comment]
@Ghoeb Si mantengo una referencia al último nodo sería O(1) para un append, pero si quiero insertar en una posición intermedia igual tendría que ir desde el primero hacia adelante o desde el último hacia atrás, quedando la complejidad O(n/2) = O(n). ¿o no?

**Comment by alopez7** [comment]
Si
