### ISSUE TITLE
Problema Creando kdTree

### ISSUE THREAD

**Issue by lsvargas** [IIC2133-PUC/2018-1#52]
Hola!

Tengo un problema al crear mi kdTree (con recursión) me tira segmentation fault y cuando corro valgrind no me tira ningun Error y el memory leak es muy poco, probe imprimiendo un dato de uno de los dos hijos del nodo raiz de mi kdTree y veo la impresion solo cuando corro el programa con valgrind.

Gracias

**Comment by lsvargas** [comment]
Si estoy seguro que termina puse prints para para un arbol de profundidad 2 y al parecer cuando retorna la raiz del arbol tira segmentation fault.

**Comment by alopez7** [comment]
Me suena a que estás incializando mal los nodos. ¿Por casualidad estás usando memoria del stack y no del heap?

**Comment by lsvargas** [comment]
Noo, mis nodos los creo asi 
`kd_Node *node = malloc(sizeof(kd_Node));`

**Comment by Ghoeb** [comment]
Chispas, suena a un problema en la separación de los poderes de C... El compilador no compila los .h, por lo que si pones cosas que no sean declaraciones vas a tener problemas. La idea es poner toda la lógica en el .c, y toda la "API" en el .h

Como estas haciendo para compilar tu programa?
