### ISSUE TITLE
Probando vecino mas cercano

### ISSUE THREAD

**Issue by gacuchac** [IIC2133-PUC/2018-1#53]
Alguien tiene una imagen png ocn pocos pixels? la más chica que encontré es de 128x128 y no puedo ver si estoy encontrando el vecino más cercano correctamente.

**Comment by alopez7** [comment]
![images](https://user-images.githubusercontent.com/11396472/38744380-12bde3ec-3f18-11e8-8a3b-9f86163878a2.png)

**Comment by gacuchac** [comment]
Lo que quería revisar eran los printf del debugging para ver como falla, al final lo mas comodo fue usar getchar()
