### ISSUE TITLE
libpng warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by gacuchac** [IIC2133-PUC/2018-1#54]
Cuando pruebo con algunos .png me sale esto. No con todos los png, solo con algunos.
Cuando no me sale esto, no se abre la ventana que muestra la imagen, pero igual se guarda en la carpeta programa la imagen teselada.
A qué se debe esto?

**Comment by alopez7** [comment]
Hay varios tipos de archivo dentro de PNG. 

La tarea se va a corregir con las imágenes que les pasamos, así que lo que importa es que funcione con esas.

**Comment by gacuchac** [comment]
pero tiene que mostrarse la imagen o van a corregir sobre la imagen guardada?
pueden subir las imagenes para saber si me funcionan y tener una nocion de cuanto se demora si programa?

**Comment by Ghoeb** [comment]
De la sección "Output" del enunciado:

> El output de tu programa debe ser la imagen filtrada mostrada en la interfaz gráfica que se te provee.

En tu repositorio venían 3 imágenes PNG dentro de la carpeta Programa/imgs: lena, mosque y rose.

En el issue #48 se muestran los tiempos relativos con distintas cantidades de núcleos para cada una de estas 3 imágenes, y como calcular esa métrica de tiempo.

Como dijo Antonio, la tarea se corregirá usando estas mismas 3 imágenes, que son las imágenes que les pasamos.
