### ISSUE TITLE
S.O a revisar

### ISSUE THREAD

**Issue by fvandeputte** [IIC2133-PUC/2018-1#55]
Hola! Al programar mi tarea la hice en una máquina virtual con Ubuntu, donde no me tira ningún error. Sin embargo, al tratar de ejecutarla en el terminal normal (tengo un MAC) me tira segmentation Fault. La tarea, será corregida en que S.O? O cual podria ser la causa del error en el terminal de Mac? Gracias

**Comment by alopez7** [comment]
Ejecutaste tu código con vlagrind en ubuntu?

**Comment by fvandeputte** [comment]
Si. Que debiese pasar?

**Comment by Ghoeb** [comment]
> donde no me tira ningún error

¿Si? Porque es valgrind el que te dice eso

> Si. Que debiese pasar?

Eso, valgrind te va a decir cuantos errores y leaks tiene tu programa. Si tiene aunque sea UN error, cabe la posibilidad de que se caiga al ejecutarlo en otra máquina.

**Comment by Ghoeb** [comment]
Los leaks son bonus, pero los errores como ya dije pueden hacer que tu programa se caiga, como acabas de ver. Si al correr un test el programa se cae, entonces tu programa no fue capaz de resolverlo, lo que significa 0 puntos en ese test. Si tienes un problema que hace que se caiga siempre, tendrás un 1 en código! (Esto es recorregible, pero segun el tamaño del error recibirás menos puntaje)

TL;DR: GO FIX YOUR PROGRAM

**Comment by fvandeputte** [comment]
Perfecto, gracias. Algun consejo para debuggear este tipo de errores? (causas, comandos de valgrind, etc)

**Comment by Ghoeb** [comment]
Valgrind te da toda la información que necesitas:

* `archivo.c:n` indica que el error esta en la línea n del archivo.c. Si eso es una llamada a otra función, va a aparecer despues de el error producido dentro de esa función (va a salir el stack de funciones)

* `invalid read at`: indica que el error se produjo al tratar de leer en memoria sobre la que no tenías permiso

* `invalid write at`: lo mismo, pero en lugar de leer, escribir

En general va a quejarse tambien de que hay memoria no inicializada: si haces malloc y tratas de leer lo que hay ahi, eso es un error de memoria porque ahí podría haber cualquier cosa.

En general, trata de resolver el primer error que aparezca en valgrind, ya que ese mismo puede estar causando los de más abajo.

Si te quedan dudas, manda una foto del output de valgrind por aquí mismo, cosa de ver cual es el primer error.

**Comment by fvandeputte** [comment]
Arregle el problema de memoria, pero sigue sin poder ejecutarse en MAC. Adjunto resultado de valgrind. 
![captura de pantalla 2018-04-15 a las 11 36 40 p m](https://user-images.githubusercontent.com/11547737/38787691-01a3f49e-4106-11e8-939d-7795cd8249e4.png)

Puedo asumir que está bien?

**Comment by Ghoeb** [comment]
Pero y que pasa en MAC? Intenta correr valgrind en MAC para saber que pasa: si bien en MAC valgrind arroja falsos positivos, siempre va a notificar acerca de los errores de verdad.

**Comment by fvandeputte** [comment]
Creo haberlo solucionado. Mire un warning que tenia y al arreglarlo se soluciono. Gracias!!
