### ISSUE TITLE
Duda nucleos

### ISSUE THREAD

**Issue by jpdattas** [IIC2133-PUC/2018-1#57]
Hola. Que pasa cuando hay 2 o más nucleos con mismo "x" o "y"? Al hacer el kdtree por ahora tengo que si los nodos inmediatamente siguientes a la mediana tienen mismo "x" (particionando segun x) o "y" (particionando segun y), se va corriendo la "mediana" al siguiente nodo.

Si esto pasa, la partición podría desbalancearse y quedar muy cargada hacia un lado. Es importante eso? Me imagino que al ser caso extremo no tiene mucha importancia. Pregunto para asegurarme.

**Comment by alopez7** [comment]
Asume que no pasa
