### ISSUE TITLE
Violación de segmento con muchos nucleos

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2133-PUC/2018-1#59]
Hola,

Cuando pruebo con 500.000 núcleos anda mas o menos bien, pero al llegar como a los 800.000 se me cae y me dice la típica violación de segmento. ¿Será esto por falta de RAM o probablemente hay un error en mi código o podría ser otra cosa?

**Comment by alopez7** [comment]
Es casi imposible que sea por ram
