### ISSUE TITLE
Funcion free() y Null

### ISSUE THREAD

**Issue by sgvasquez** [IIC2133-PUC/2018-1#6]
Hola!

Si quiero eliminar el último nodo en una lista ligada, donde nodoPrevio apunta a Nodo, cual es la forma correcta de hacerlo?

Se hace así:

- Eliminar Nodo (free(Nodo))

- Hacer que la referencia sea nula (nodoPrevio->next = Null)

O solo con free(Nodo) basta?

Gracias!

**Comment by Ghoeb** [comment]
`free(Nodo)` devuelve la memoria al sistema operativo, pero no setea a Nodo como NULL, es decir ahora Nodo apunta a una dirección de memoria inválida.

Asi que, debes liberar la memoria Y setear la referencia a NULL, ya que sino tu programa se va a caer al tratar de detectar cual es el último elemento de la lista.

**Comment by sgvasquez** [comment]
Gracias!
