### ISSUE TITLE
Errores de Memoria

### ISSUE THREAD

**Issue by ManuelBeckerT** [IIC2133-PUC/2018-1#61]
Estoy revisando con valgrind el manejo de memoria. Me aparece que no existen memory leaks, pero sí aparecen errores por uninitialized value. Siguiendo el error desde main, llego a la función checkSubTree que tiene el siguiente código:
	if (leftResult == -1 && rightResult == -1){
		return point;
	}
Siendo leftResult y rightResult variables de tipo int que están inicializadas con -1 más arriba en el código, y en caso de que durante la recursión de checkSubTree se retorne un valor, se reemplaza el -1 por el valor. Este caso ocurre para 10.000 núcleos y son 4 errores en total. En el caso de 50.000, 100.000, 250.000 y 1.000.000.000 núcleos no hay ningún error de memoria. 
No estoy entendiendo el origen del error en memoria que da valgrind para 10.000 núcleos. ¿Tienen alguna recomendación para revisar este tipo de casos?
Aquí está el resultado de valgrind. 

![valgrinderror](https://user-images.githubusercontent.com/12106571/38846575-736be3c0-41d3-11e8-8cf8-5157b426b29d.png)

Muchas gracias

**Comment by alopez7** [comment]
Fíjate que en el mismo error dice donde se reservó esa memoria:
Uninitialised value was created by a stack allocation at main.c 553
Seguro que siempre inicializas su valor?
No lo definiste como int var;?

**Comment by ManuelBeckerT** [comment]
No estaba inicializado originalmente y luego lo inicialicé con -1 (es una variable de tipo int) y luego se cambia su valor al encontrar el nucleo que está más cercano.
Finalmente, el valor no inicializado es una variable tipo int que tendrá el valor del indice que se obtenga después de la recursión, una vez revisado los núcleos de las cajas que tengan colisión. Inicializar la variable no hizo diferencia, pero el programa nunca retorna el valor -1 para ninguna cantidad N de núcleos.
