### ISSUE TITLE
Errores aleatorios?

### ISSUE THREAD

**Issue by jpdattas** [IIC2133-PUC/2018-1#62]
Hola. Probando mi funcion para crear el kdtree me fije que a veces me funciona y a veces no. Lo pruebo con 3000 nucleos y seed 1 siempre (con ambos resultados). Sin siquiera hacer make de nuevo. Lo único aleatorio es la creacion de los nucleos (que ni siquiera es realmente aleatoria).

Alguna idea de por que podria pasar esto? al usar valgrind y con mis testeos me doy cuenta que A VECES se queda "pegado en un nodo"(al parecer particiona mal), pero ni siquiera en mi quickselect tengo aleatoriedad. todas mis funciones son deterministicas.

Al corregir se prueba una sola vez? Es muy raro

Edit: 
Probandolo hartas veces ahora al usar valgrind funciona siempre. Y sin usar valgrind no funciona. Ademas no se ha vuelto a particionar mal. Creo que puede ser solamente por falta de memoria.
Antes me estaba funcionando siempre que lo probaba sin valgrind.

**Comment by alopez7** [comment]
Pero al correrlo con valgrind te dice de algun error?
Suena a error de memoria

**Comment by jpdattas** [comment]
no dice ningun error en valgrind. ni leaks siempre que lo probé desde entonces funcionó bien en valgrind. A veces falló sin valgrind dando segmentation fault

**Comment by jpdattas** [comment]
Tenia unos problemas. Creo queno me salian al principio o quizas no me fije nomas. era raro por que a veces funcionaba pero ya lo arreglé. gracias igual
