### ISSUE TITLE
Dudas Informe

### ISSUE THREAD

**Issue by PabloAbara** [IIC2133-PUC/2018-1#63]
Hola, quería preguntar algunas cosas. 

1) Al variar el tamaño de imagen, ocupamos las 3 que nos dan nomás? O tenemos que probar más? 

2) Tenemos que estimar la complejidad de nuestro algoritmo? O se espera que expliquemos "en palabras" por qué se demora más o menos ante el análisis de sensibilidad? 

3) Es relevante explicar el funcionamiento de nuestro algoritmo y las structs (tanto las que venían como las agregadas?) O no apunta a eso el informe? 

Gracias!

**Comment by eiherrera** [comment]
Hola! 

La idea es que a través de la lectura de tu informe se alcance una comprensión completa del caso planteado en la tarea, con un enfoque en los conociemientos y objetivos del curso. Así, de manera general, te recomiendo que al momento de ver qué incluir en el informe pienses en cuál es la mejor manera de alcanzar lo antes mencionado.

Ahora, respondiendo a tus preguntas de forma particular:

1. Las imágenes entregadas varían bastante en cantidad de pixeles, por lo que son una buena muestra, pero utilizar otras más significa un mayor respaldo a los eventuales análisis que hagas.

2. Un cálculo bien fundamentado de la complejidad del algoritmo es un argumento sólido sobre las implicancias de este, pero, si con palabras explicas de forma clara, formal y bien arguentada por qué el algoritmo toma el tiempo que toma podrías lograr el mismo resultado.

3. Es muy importante explicar de forma general el algoritmo utilizado. Para lograr esto quizás sea necesario explicar también qué estructuras fueron utilizadas, al menos explicando cómo y por qué estas participaron en el algoritmo.

Espero haber aclarado tus dudas, éxito!

**Comment by alainrochette** [comment]
Y para cuándo es el informe (con hora)?

**Comment by alopez7** [comment]
Viernes a las 11:59

**Comment by Ghoeb** [comment]
Ojo, 11:59 PM (23:59)
