### ISSUE TITLE
Posibilidad de extender plazo de entrega de código (T1)

### ISSUE THREAD

**Issue by MortizDX** [IIC2133-PUC/2018-1#64]
Sé que resulta inadecuado consultar esto el mismo día de la entrega, pero quería preguntar si sería posible que dieran unos días más para terminar el código de la tarea.

Desconozco la situación total del curso, pero sé la de algunos estudiantes que se encuentran complicados con siquiera resolver el problema inicial, por lo que aunque terminen el código para la fecha del informe, es probable que el informe no lo puedan hacer tampoco.

No es la idea tampoco que se desperdicie el tiempo que ya le dedicaron los que están al día y que por terminar a la fecha tengan que esperar más tiempo para el enunciado de la siguiente tarea, así que pensaba si podían dar tiempo para que cuadre con la del informe, o que si pueden dar más tiempo para el informe, pero que se suba la tarea siguiente como siempre (así se sigue con el calendario que tenían planificado).

**Comment by Ghoeb** [comment]
Entiendo que han sido semanas dificiles, pero desgraciadamente no podemos dar más plazo para la tarea. Traten de aprovechar las próximas tareas para repuntar.
