### ISSUE TITLE
Informe duda

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2133-PUC/2018-1#66]
Hola,
¿El main tema del informe tiene que ver más con el tiempo de la búsqueda de núcleos más cercano o también con el tiempo de construcción del árbol?
Grax

**Comment by alopez7** [comment]
Si, tu análisis debe estar más enfocado a la búsqueda, ya que esta se hace N X M veces mientras que la construcción solo una vez.

**Comment by jorgeriesco** [comment]
Gracias!

**Comment by roy350** [comment]
Entonces simplemente la construcción del árbol no la incluimos dentro del tiempo?

**Comment by eiherrera** [comment]
Si es necesario mencionar el tiempo de construcción del KD-Tree.

**Comment by Ghoeb** [comment]
Si, nos interesa que hablen de la complejidad teorica en ambos casos, y que la comparen con un análisis empírico.

Traten de medir los tiempos por separado, ya que cargar y mostrar la imagen tambien toma su tiempo, y eso no nos interesa.
