### ISSUE TITLE
Complejidad qsort

### ISSUE THREAD

**Issue by roy350** [IIC2133-PUC/2018-1#68]
Hola! en la solución de la tarea se uso qsort para ordenar el arreglo, y googleando no encontré su complejidad y la necesito para hacer cierto análisis en la construcción del árbol, si alguno la supiera estaría muy agradecido!

**Comment by alopez7** [comment]
Hola, qsort hace quicksort eligiendo pivote random y luego hace i sertion sort para los arreglos chicos. Es O(n log(n)) en caso promedio.

**Comment by roy350** [comment]
muchas gracias! :)
