### ISSUE TITLE
Informe Tarea 1

### ISSUE THREAD

**Issue by ManuelBeckerT** [IIC2133-PUC/2018-1#69]
Mi código es capaz de trabajar con 250.000 núcleos en el tiempo requerido por la tarea. Ahora, al momento de graficar los resultados, no veo ninguna relación de los tiempos obtenidos para encontrar el núcleo más cercano. Puedo presentar los datos tal y como me los entrega mi código para realizar el análisis del informe? Ya que cumple los requerimientos de tiempo, me parece que al menos el código debería cumplir con la complejidad teórica y mostrar los resultados que obtengo sería válido. Alguna recomendación? 
Gracias

**Comment by eiherrera** [comment]
¡Hola! 

Recuerda que existe una solución pública a la tarea, la cual pueden usar como apoyo, referencia y comparación para efectos del informe. Creo que en este caso te podría servir usarla.

De todas formas, utiliza también los resultados obtenidos por tu implementación, y en caso de tener diferencias con lo esperado teóricamente o lo que ocurre con la solución, basta con aclarar bien qué es lo esperado, por qué y explicar por qué se llegó a algo distinto.

**Comment by ManuelBeckerT** [comment]
Dale, muchas gracias.

**Comment by Ghoeb** [comment]
Digamos que tu calculaste que la búsqueda se demoraba una función de los pixeles y núcleos F(P,N).

¿A la hora de cambiar P y N, se ajustan los tiempos reales de ejecución a esa función teórica que calculaste? ¿Que pasa si graficas ambas? 

Y bueno, en base a las respuestas a esas preguntas, haz un análisis.
