### ISSUE TITLE
Sin github

### ISSUE THREAD

**Issue by lfbesa** [IIC2133-PUC/2018-1#7]
No alcance a responder el cuestionario del siding por lo que no me asignaron un repositorio para subir mi actividad. ¿Qué hago?

**Comment by alopez7** [comment]
Aun no se crean los repositorios, lo vas a tener antes del otro domingo, gracias por avisar

**Comment by asimonv** [comment]
Debería llegar un mail?

**Comment by alopez7** [comment]
Les haremos saber cuendo tengan su repositorio

**Comment by dagalloso** [comment]
En ese caso van a abrir un nuevo cuestionario para enviar el usuario?

**Comment by iqacevedo** [comment]
Hola yo respondí el cuestionario pero aun no tengo repositorio, ¿Que puedo hacer?

Saludos !

**Comment by Ghoeb** [comment]
@iqacevedo [no?](https://github.com/IIC2133-PUC/iqacevedo-A0-IIC2133-PUC-2018-1)

**Comment by iqacevedo** [comment]
Ahora si muchas gracias !

**Comment by vjmoreno** [comment]
@Ghoeb yo tambien estoy sin repositorio

**Comment by Mapuentes** [comment]
@Ghoeb yo tampoco tengo

**Comment by Ghoeb** [comment]
Están creados desde el dia que antonio aviso. En el mail aparece como encontrarlos.
