### ISSUE TITLE
Estudio I2

### ISSUE THREAD

**Issue by sebacruzd** [IIC2133-PUC/2018-1#70]
Hola,

Estoy repasando de las clases y quería complementar con las [clases del MIT](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-006-introduction-to-algorithms-fall-2011/lecture-notes/) que para la I1 justo eran de la 1 a la 6.
Ahora ya no es exactamente desde la 7 hasta alguna otra (creo).
Cuáles recomendarían revisar, viendo los nombres de las clases?
No las he visto aún, pero creo que podrían ser:
8-9-10(?)-13-14

Gracias de antemano!

**Comment by eiherrera** [comment]
Hola!

Me parece que las que mencionas efectivamente te son útiles. Eso sí, si no me equivoco, en clases vieron también backtracking, lo que no aparece ahí, para que no te olvides de estudiarlo. 

Además, en caso de que quieras más material de estudio, no puedo dejar de recomendar [Introduction to algorithms](http://ressources.unisciel.fr/algoprog/s00aaroot/aa00module1/res/%5BCormen-AL2011%5DIntroduction_To_Algorithms-A3.pdf) de Thomas Cormen. Muy buen libro.

Éxito con el estudio!

**Comment by sebacruzd** [comment]
Gracias Eugenio!

**Comment by Ghoeb** [comment]
Y bueno, ya está subida la clase del miércoles también.
