### ISSUE TITLE
Dónde estudiar Backtracking

### ISSUE THREAD

**Issue by sgvasquez** [IIC2133-PUC/2018-1#73]
Eso, tengo entendido que no está en el Cormen, y no sé si solamente baste lo que sale en las diapos :)

Gracias!

**Comment by Ghoeb** [comment]
En las diapos está todo. Asegurate de leer las notas de cada diapo, y preguntar cualquier duda en la clase del miércoles.

**Comment by sgvasquez** [comment]
Gracias!

**Comment by Ghoeb** [comment]
Otra cosa que puedes hacer es ejercicios... [acá ](https://en.wikipedia.org/wiki/List_of_NP-complete_problems) hay una lista de problemas que tiene sentido resolver con backtracking: 

Para cada uno de ellos, preguntate:
1) Cuales son las variables
2) Cuales son sus dominios
3) Cuales son las restricciones
4) Qué podas podrían tener sentido, y
5) Qué heurísticas podrían tener sentido

**Comment by sofizambrano** [comment]
[Backtracking.pdf](https://github.com/IIC2133-PUC/2018-1/files/1999386/Backtracking.pdf)
 Esta guía a mi me sirvió harto!
