### ISSUE TITLE
Clases de Hash no tienen versión en PDF

### ISSUE THREAD

**Issue by MortizDX** [IIC2133-PUC/2018-1#74]
Quería comentar lo que dice el título, ya que no puedo ver el formato pptx con Ubuntu (al menos con el programa que viene por defecto... y técnicamente se puede "ver", pero aparece todo el texto desordenado/repetido).

**Comment by Ghoeb** [comment]
Chuta, se me pasó eso y las subí en PPTX. Ahi lo arreglé, ya estan en PDF.

**Comment by MortizDX** [comment]
Muchas gracias :)
