### ISSUE TITLE
Ayudantía o Cátedra hoy? (04/05)

### ISSUE THREAD

**Issue by MortizDX** [IIC2133-PUC/2018-1#75]
No sé si lo mencionaron en la última clase, pero quería consultar eso. Pensaba que ayudantía no podría haber, ya que tuvimos la de la tarea 2 hace poco y tampoco hemos visto más materia posterior a la prueba... pero me queda la duda si habrá clases de cátedra entonces.

**Comment by alopez7** [comment]
No hay nada mañana

**Comment by MortizDX** [comment]
Oh, ok, gracias por aclarar tan rápido ^^
