### ISSUE TITLE
Puntaje Preguntas I1

### ISSUE THREAD

**Issue by Dalal15** [IIC2133-PUC/2018-1#76]
Hola,

En la pauta que subieron de la I1 no me queda claro el puntaje asignado a cada subpregunta. Podrían aclarar eso? Específicamente en la pregunta 2.

Gracias!

**Comment by alopez7** [comment]
@nissimergas

**Comment by nissimergas** [comment]
Cada subpregunta tiene 2 puntos.
a) 1 punto por cada altura completamente correcta, entre 0.3 y 0.5 por medianamente correcta, 0 por incorrecto
b)  2 puntos por llegar a la h esperada, entre 1 y 1.5 por tenerla con algunos errores, 0 por equivocaciones graves
c) 1 por qué el algoritmo este bien (con su complejidad) pero no sea la eficiencia esperada, 2 si es que es lo esperado, 0 si está mal o es ineficiente

**Comment by Dalal15** [comment]
Muchas gracias!
