### ISSUE TITLE
Duda poda T2

### ISSUE THREAD

**Issue by kpribbeck** [IIC2133-PUC/2018-1#77]
Hola, mi duda es qué se considera como poda y qué no. Específicamente, si en backtracking elijo para asignar una celda que tiene degree 2 y decido pintarla de amarillo, porque la suma de sus adyacentes del mismo color es menor o igual a dos, pero justo a la derecha hay una celda con degree = 4 de color azul. Entonces, notar que esta no es una asignación correcta se considera una poda, o es parte de las restricciones del problema? Esto pensando para correr el programa con y sin podas con el fin de compararlos. Gracias

**Comment by alopez7** [comment]
Si no es una restriccion implicita, es una poda

**Comment by Ghoeb** [comment]
Hola, eso es una poda, ya que aun no sabes si los vecinos de esa celda son todos de su mismo color, pero como tu mismo lo dices, ya no puede serlo. La restricción simplemente dice que el grado de una celda debe ser igual a la cantidad de vecinos de su mismo color, no por ejemplo que una celda 4 no puede tener dos vecinos de colores distintos, o una celda 2 no puede tener 3 o 4 vecinos de un mismo color.
