### ISSUE TITLE
Repo T2

### ISSUE THREAD

**Issue by gbordoni** [IIC2133-PUC/2018-1#78]
Nos darán repo para la tarea 2?

**Comment by Ghoeb** [comment]
Deberia haberles llegado este aviso con la publicación de la T2:

> Hola

> Cree su repositorios para la tarea 1. Sus repositorios tienen la siguiente estructura: Usuario-T2-IIC2133-PUC-2018-1
>Si no les llega la invitación a su repositorio puden buscarlo con el link https://github.com/IIC2133-PUC/usuario-T2-IIC2133-PUC-2018-1 (remplazando "usuario" con su usuario de github).

>Si aún así no lo encuentran, manden un mail inmediatamente para no estar creado los repositorios a última hora.

>Saludos

Y bueno, ups, dice Tarea 1 al principio, pero se envió al publicar la T2.
