### ISSUE TITLE
Numero en los bordes tarea 2

### ISSUE THREAD

**Issue by roy350** [IIC2133-PUC/2018-1#79]
Hola! me queda la duda si es posible que haya algun numero en los bordes? porque si o si parte todo el borde de color amarillo(alianza), entonces nos podrían poner un número ahí? es para saber si los bordes no me preocupo de incluirlos en la parte del backtracking cuando estoy buscando el degree de la casilla. Muchas gracias!

**Comment by asdegoyeneche** [comment]
Hola! No, en los bordes no habrán números. Y para confirmar, sí, siempre los bordes serán amarillos. 
Saludos!

**Comment by roy350** [comment]
Gracias!
