### ISSUE TITLE
Valgrind

### ISSUE THREAD

**Issue by yoavnavon** [IIC2133-PUC/2018-1#8]
Hola, estoy un poco confundido con el uso de valgrind. Cuando hago:
`valgrind /.listas` en un programa que utiliza las funciones pedidas me aparece:

```
LEAK SUMMARY:
definitle lost: 0 bytes in 0 blocks
indirectly lost: 0 bytes in 0 blocks
possibly lost: 72 bytes in 3 blocks
still reachable: 200 bytes in 6 blocks
suppressed: 22,057 bytes in 151 blocks

ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 4 from 4)

```

Pero si ejecuto un programa que no tiene nada en el main excepto el `return 0;`, me aparece practicamente el mismo aviso:

```
LEAK SUMMARY:
definitle lost: 0 bytes in 0 blocks
indirectly lost: 0 bytes in 0 blocks
possibly lost: 72 bytes in 3 blocks
still reachable: 200 bytes in 6 blocks
suppressed: 17,961 bytes in 150 blocks

ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 4 from 4)

```

Que significa esto? Los possibly lost significan que de todas maneras estoy teniendo leaks aunque mi programa no haga nada?

**Comment by alopez7** [comment]
¿En qué sistema operativo estás trabajando?

**Comment by yoavnavon** [comment]
Lo había probado en Mac, ahora con tu comentario lo probé en ubuntu y apareció que no habían leaks. Veo que el build de valgrind pa mac no funciona bien. Gracias!!
