### ISSUE TITLE
Sobre regresar a estados anteriores

### ISSUE THREAD

**Issue by roy350** [IIC2133-PUC/2018-1#80]
Disculpe, pero me queda la duda con la función ```watcher_set_cell_status(int row, int col, bool is_rebel );``` ya que esta es la que pinta los tableros dependiendo de a que grupo pertenece, pero cuando necesite devolverme a un estado anterior y esta casilla era de color "neutro"(por decirlo de alguna forma), como vuelvo a ese color? ya que solo puedo pintarlo de alianza o de rebelión, o lo importante no es volverlo a pintar si es que lo tengo identificado de otra forma con un atributo de una struct? Finalmente importa los colores con que vaya pintando en el progreso de mi algoritmo o solo importa que llegue a los colores finales correctos? Muchas gracias por todas estas preguntas!

**Comment by Ghoeb** [comment]
La función `watcher_clear_cell(int row, int col)` es la encargada de pintar la celda como "neutra".

Lo unico que importa es que al llamar a la función `watcher_close()` los colores en la interfaz sean correctos. 

De hecho, no recomiendo mostrar cada paso intermedio en la versión final de tu código, ya que agrega un delay innecesario a tu programa.
