### ISSUE TITLE
Tests dificiles

### ISSUE THREAD

**Issue by kpribbeck** [IIC2133-PUC/2018-1#81]
Hola, van a subir los tests más dificiles que mencionaron en un momento? Los que se usan para el bonus o similares a estos. Gracias

**Comment by Ghoeb** [comment]
Si, estarán hoy :)

**Comment by kpribbeck** [comment]
Gracias!

**Comment by Ghoeb** [comment]
[Listo](https://github.com/IIC2133-PUC/2018-1/tree/master/Tareas/Tarea%202/tests/lunatic)

**Comment by sofizambrano** [comment]
Hola! Dentro de cuántos segundos se debe obtener el output para los tests lunatic del bonus?
