### ISSUE TITLE
Cairo-pdf

### ISSUE THREAD

**Issue by nachojarasaez** [IIC2133-PUC/2018-1#82]
Hola, tengo el siguiente problema. Al ejecutar el comando make de los archivos entregados me arroja el error de fatal error: 'cairo-pdf.h' file not found. He instalado Cairo y me sigue arrojando error. Ayer estuve todo el día en esto y no puedo comenzar. Atento a su respuesta. De antemano gracias.

**Comment by alopez7** [comment]
Necesito mas información.
1. ¿En qué sistema operativo estás trabajando?
1. ¿Instalaste bien la librería de GTK?
1. Por favor manda un screenshot del error al tratar de compilar.

**Comment by nachojarasaez** [comment]
Ya solucionado, me faltaba configurar el GTK. Gracias
