### ISSUE TITLE
watcher_close no me funciona

### ISSUE THREAD

**Issue by PabloAbara** [IIC2133-PUC/2018-1#83]
Hola! Tengo una duda, me pasa que si le quito el "sleep(1)" a mi main.c, el watcher_close deja de funcionar 🤔 . ¿Cuál puede ser el problema?

EDIT: Pasa sólo en los 'easy'

**Comment by PabloAbara** [comment]
Pero se me queda pegado, no es que se cierre. Y si le pongo un sleep, funciona. Y si hago los normal, funciona. 
¿Qué se hace? Quizás efectivamente sea porque es rápido, pero no alcanza a cachar que se abrió, entonces no lo .. cierra? 

Gracias

**Comment by alopez7** [comment]
Para trabajar usa el sleep y cuando lo mandes quítalo. Y si te complica por el tiempo puedes comentar todo lo que sea del warcher. Cuando mandes tu tarea vuelves a poner el watcher

**Comment by Ghoeb** [comment]
A la hora de corregir las llamadas a watcher en realidad interactuarán con el corrector. A veces la libreria que usamos para la interfaz grafica tiene problemas, pero no te preocupes por eso mientras estes dibujando bien la solución antes de llamar watcher_close

**Comment by PabloAbara** [comment]
Vale gracias! de todos modos con un Snapshot como creo que funciona. Para la entrega dejamos sólo el watcher_close entonces. (igual, es bastante irrelevante).

**Comment by alopez7** [comment]
Para la entrega deja todas las funciones del weather
