### ISSUE TITLE
Problemas con Watcher_Snapshot

### ISSUE THREAD

**Issue by fvandeputte** [IIC2133-PUC/2018-1#84]
Hola! Al ejecutar el codigo y llamar a la funcion watcher_snapchot, el pdf generado sale "borroso", adjunto pantallazo de pdf. (Como se mejora?)
![captura de pantalla 2018-05-14 a las 11 36 35 p m](https://user-images.githubusercontent.com/11547737/40035438-cd76db60-57cf-11e8-82bb-3b31138042ce.png)

**Comment by Ghoeb** [comment]
Eso es culpa de tu visor de PDF. Prueba abrirlp con otro.

**Comment by fvandeputte** [comment]
Gracias! Eso era
