### ISSUE TITLE
Sobre los tiempos de los tests

### ISSUE THREAD

**Issue by MortizDX** [IIC2133-PUC/2018-1#85]
Tenía la duda si acaso los tests que subieron (los de la dificultad original, no el "lunático"), para que sean resueltos en 10 segundos, fueron hechos considerando solo las podas que indicaron en el enunciado o se esperan muchas más podas (o incluso heurísticas). Lo pregunto porque he estado varios días viendo como mejorar mi programa para que superen lo más difíciles, pero siento que no he avanzado nada y a lo mejor he implementado mal una poda anterior, así que quería tener claro eso al menos.

**Comment by alopez7** [comment]
Se espera que con las podas nombradas se pueda resolver todo.

**Comment by Ghoeb** [comment]
El detalle es implementar cada poda de manera eficiente.

**Comment by MortizDX** [comment]
Oka, voy a revisar bien mi código que tenía antes para mejorarlo. Muchas gracias!
