### ISSUE TITLE
Comparación con podas y sin podas

### ISSUE THREAD

**Issue by lfbesa** [IIC2133-PUC/2018-1#86]
Para realizar el informe dice que debemos comparar la ejecución con las podas del enunciado y sin las podas (para lo que teníamos que ser ordenados con el código). ¿Qué pasa si la única forma que encontré para asegurar que se cumpliera la restricción de los dos grupos es esa poda? Sin darme cuenta programe esa poda como parte del programa inicial para solo cumplir la restricción, por lo que no puedo hacer una comparación sin esa poda.
¿Qué se hace con el informe en ese caso?

**Comment by alopez7** [comment]
Comprueba qué pasa si no usas la restricción y la controlas al final de la ejecución

**Comment by fvandeputte** [comment]
Con respecto a eso,
Cuando comparamos la ejecucion SIN podas, debemos probar todas las asignaciones (fuerza bruta) y luego verificar que para cada "hoja" del arbol(o combinacion) se cumplan las restricciones??

**Comment by alopez7** [comment]
No podar no significa hacer fuerza bruta cuidado con eso. Comprobar que se cumplan las restricciones no es una poda. Tu programa sin podas no debería hacer asignaciones que rompan una restricción. Las podas te permiten identificar cuando llegarás a un estado sin solución en el futuro.

**Comment by sgvasquez** [comment]
No sé si entiendo bien, pero sin podas es como decir "mi posición no hace que YO rompa ninguna asignación AHORA"?, y hacerlo con podas es como decir "mi posicion no hace que NADIE rompa ninguna asignación NUNCA?"

Por que estoy igual que @fvandeputte, en el sentido que hice la poda (de vecinos en mi caso) en un inicio porque no se me ocurre como hacerlo sin ella.

**Comment by alopez7** [comment]
No necesariamente. Hay podas simples que descartan asignaciones que no llevan a  una solución mirando solamente sus vecinos. Evidentemente que podas que miran más partes del tablero podrían descartar más. Pero esto tiene un costo mayor y seguramente tampoco es simple de hacer

**Comment by Ghoeb** [comment]
@TamaraCucumides no, eso no es necesario. solo tienes que revisar las celdas que podrían haber violado una restricción luego de hacer la asignación, en el caso de este problema, la celda recién asignada, y sus vecinos.

**Comment by fcgfaura** [comment]
@Ghoeb lo que recién describes, sería para cumplir con la restricción, o para hacer la poda ?, me suena más a restricción. O la restricción en este caso se debe ver al final de todas las asignaciones?

**Comment by nachojarasaez** [comment]
Hola respecto a eso, si subo el código con las podas implementadas debo indicar que debo retirar del código para no aplicar las podas, o el código sera evaluado con las podas. Esto lo pregunto dado que lo implemente directamente con las podas y estoy corto de tiempo para adaptar el código para ambas.

**Comment by alopez7** [comment]
No, el código debes subirlo con la versión más rápida que tengas funcionando.
Para el informe puedes modificar tu código para hacer los análisis correspondientes.

**Comment by MortizDX** [comment]
Para aclarar, que aún me confunde la diferencia entre una poda y una restricción para la condición que dan los vecinos: si al querer ver que valor asigno a una celda en particular que no infrinja la restricción de vecinos ¿ver solo la restricción en esa celda bastaría como una simple restriccción? ¿o sería una restricción incompleta? Porque poner una celda cerca de otras ya asignadas con anterioridad, es posible que se infrinja el estado actual por culpa de la nueva.

O por ejemplo, si pongo una celda en (x,y), y si bien no se ha "roto" nada, si veo la condición de sus vecinos, sé que si sigo con ese estado, no llegaré a una solución válida (por que digamos que hay un de grado 4 y por culpa de la nueva, quedarían 2 vecinos distinos alrededor de él, aun si no se ha llenado por completo sus vecinos) ¿eso sería restricción solamente o pasa a ser poda?

**Comment by MortizDX** [comment]
Entonces en el caso del enunciado, es poda porque el nodo central (con grado 4) no tiene asignado un valor, pero si sus vecinos?

**Comment by alopez7** [comment]
Es una poda ya que no están asignados todos los valores de la restricción. Si el 4 fuera asignado igual sería una poda, ya que aún tiene vecinos sin asignar.

**Comment by MortizDX** [comment]
Aah, y si la celda y todos son vecinos están asignados, revisar eso sería verificar la restricción?

**Comment by alopez7** [comment]
Si
