### ISSUE TITLE
Tiempo de ejecución 

### ISSUE THREAD

**Issue by nachojarasaez** [IIC2133-PUC/2018-1#88]
Hola quiero saber que tan estrictos son con los 10 segundos de ejecución. Dado que 2 de los test me corren con 13 y 15 segundos. Los demás todos bajo 10. Que ocurre en estos casos??

**Comment by alopez7** [comment]
100% estrictos. Tu código lo corre un programa sin piedad. Considera mejorar tu solución si no estás logrando los tiempos
