### ISSUE TITLE
Argumentos extra para las funciones

### ISSUE THREAD

**Issue by kpribbeck** [IIC2133-PUC/2018-1#9]
Hola, tengo la duda de si las funciones tienen que tener exactamente la estructura que nos pasaron, o podemos pasarles argumentos extra, o hacer que retornen cosas (en el caso de las funciones void).

**Comment by kpribbeck** [comment]
Otra cosa, los array deben ser compactos? es decir, si tengo [1, 2, 3, 4] y borro el 2, entonces me queda [1, 3, 4] o [1, NULL, 3, 4]

**Comment by Ghoeb** [comment]
1) Explica de que caso hablas
2) Deben ser compactos. Despues de todo, NULL no es un int, por lo que no puedes ponerlo en un arreglo.

**Comment by nivek0o0** [comment]
Hola, yo tengo la misma pregunta (1). 
¿Podemos modificar los parámetros de las funciones, es decir, modificarlas en el header?
Específicamente en el caso de las funciones insert y delete, donde solo puedo insertar/eliminar un elemento en la posición 0 si la **list** se pasa a la función por referencia y no por valor, y así poder actualizar el puntero del main.

**Comment by Ghoeb** [comment]
@nivek0o0 No, no puedes modificar los header de las funciones. Despues de todo, la función que crea una lista te la debería entregar en el formato que necesitas para usarla en las otras funciones.

**Comment by nivek0o0** [comment]
¿Entonces cómo se puede actualizar el puntero del main desde adentro de la función insert?
Porque al insertar un elemento en la posición 0, el puntero del main sigue apuntado al elemento que ahora queda en segunda posición. 
Se me ocurre, tanto en arraylists como linkedlists, mover todos los valores para que el puntero apunte efectivamente al primer valor, pero esto sería sumamente costoso [O(n)] para una operación tan simple  como crear un nodo y actualizar un par de referencias [O(1)].

**Comment by alopez7** [comment]
Explícate mejor, de qué puntero estás hablando

**Comment by nivek0o0** [comment]
Muchas gracias, ya encontré la manera de implementar la operación, pero explicaré mi duda de todas formas. 

Cuando hacemos 
```
LinkedList * testeo = linkedlist_init();
linkedlist_append(testeo, 5);
linkedlist_insert(testeo, 4, 0);
```
la función insert, dentro de su scope, no tiene como modificar la dirección de memoria del puntero **testeo** al haberselo pasado por valor y no por referencia, por lo que **testeo** seguirá apuntando hacia la estructura con valor 5 luego del insert. Había que ser más ingenioso que simplemente colocar una estructura delante del 5 e intentar mover el puntero :sweat_smile:

**Comment by Diiru** [comment]
Siguiendo lo que se dijo de "compacto"; al hacer arraylist_delete a un array, por ejemplo [2, 3, 4, 5], con largo=4. Si borro el 2, queda [3, 4, 5], pero el delete no afecta su largo, cierto ? Quedaría [3, 4, 5, 0] ? O cambiaría su largo a 3, cortando la lista ?

**Comment by alopez7** [comment]
El largo del arreglo debe quedar igual, pero tu debes saber (porque tienes la variable count) cuantos datos tienes. En ese caso puedes dejar el arrelgo como [3, 4, 5, cualquiercosa]
