### ISSUE TITLE
"Análisis teórico y empírico"

### ISSUE THREAD

**Issue by PabloAbara** [IIC2133-PUC/2018-1#90]
Hola! 

En las instrucciones del informe piden hacer un análisis teórico y empírico de nuestra solución. En primer lugar, entiendo que esto sólo aplica a la comparación del desempeño al agregar las podas v/s sin podas, o no? . En segundo lugar, con análisis teórico se refieren a explicar su complejidad? O a dar un entendimiento de por qué la poda será más o menos potente en cuanto al "árbol que genera", pero con una explicación no necesariamente matemática...me explico? 

Gracias!

**Comment by alopez7** [comment]
Se sabe que los problemas que se pueden resolver con backtracking en general se resuelven en tiemo exponencial, por lo que la complejidad no es tan importante.
Es muy dificil calcular la complejidad exacta de un oproblema con podas o heurísticas, por lo que explicar intuiciones de porqué  mejora o no es mejor opcion

**Comment by alopez7** [comment]
Vas a tener que comparar con y sin heurístiva
