### ISSUE TITLE
Podas y propagación

### ISSUE THREAD

**Issue by josemlira** [IIC2133-PUC/2018-1#91]
Hola! Para la entrega final sale que hay que tener como mínimo las podas de colores y grupos de vecinos, pero revisando mi programa, luego de hacer propagación, ya no sirve la poda de colores (dado que la propagación ya le dice con anticipación a las celdas qué valores puede tomar). Puedo quitar esa poda de mi programa final, ya que solo quita tiempo? (claramente para el informe guardaré una versión que sí tenga la poda).

**Comment by alopez7** [comment]
Te recomiendo que subas la version mas rápida de tu programa y luego en el informe discutes sobre la poda y propagación.
