### ISSUE TITLE
Recorrección A0 y T1

### ISSUE THREAD

**Issue by isidoravs** [IIC2133-PUC/2018-1#93]
Hola, me gustaría saber si ya están subidas todas las notas luego de la recorrección de la A0 y si abrirán un cuestionario para recorregir la parte del informe de la T1.

Muchas gracias!

**Comment by alopez7** [comment]
Hola, ya está recorregida la A0. Cuando estén todos los informes de la tarea 1 se va a abrir un cuestionario.

**Comment by gacuchac** [comment]
En la planilla aparece como que no entregue el código, pero está en mi repo.

**Comment by alopez7** [comment]
@gacuchac  Resolví el problema. Lo que pasa es que la fórmula de la planilla no detectaba tu número de alumno porque parte con un 0. Te fue muy bien.
