### ISSUE TITLE
Output programa T02

### ISSUE THREAD

**Issue by sebacruzd** [IIC2133-PUC/2018-1#94]
En el enunciado dice:
`"El output de tu programa serán los valores que estén en la ventana cuando se llame a watcher close."`
No me queda 100% claro qué debe ser el _output_, y del issue #83 no resolví mis dudas.
Por ahora estoy haciendo:
```c
watcher_snapshot("output.pdf");
usleep(10);  // le pongo este microsleep para que no se quede abierto (a veces no se cierra si no se espera nada.)
watcher_close();
```
Lo del _snapshot_ está bien o lo saco?

Gracias de antemano.

**Comment by alopez7** [comment]
Saca el snapshot y el sleep

**Comment by sebacruzd** [comment]
No importa para la corrección que a veces cuando no está ese sleep no se cierre la ventana? No se por qué pasa eso.
En todo caso el sleep son 10 microsegundos.

**Comment by alopez7** [comment]
Lo que pasa es que para corregir yo modifico el watcher.c, por lo que ya no se abre la ventana sino que se guarda una imagen en un archivo. Entonces solo importa que llames las funciones.

**Comment by sebacruzd** [comment]
Perfecto, gracias!

**Comment by ManuelBeckerT** [comment]
Entonces ustedes van a tomar el último estado del watcher y obtendrán así nuestro output? No voy modificando la interfaz durante la ejecución. Lo hago una vez obtenida una solución.

**Comment by alopez7** [comment]
Tu output debe ser el output final en la ventana. Da lo mismo si en la ejecución pones otras cosas. Solo se toma la version final.
Es muy importante que hagan watcher close porque ahí yo guardaré el output en un archivo
