### ISSUE TITLE
Cantidad de devoluciones

### ISSUE THREAD

**Issue by NachoCasta** [IIC2133-PUC/2018-1#99]
A que se refieren con "cantidad de devoluciones" en la parte de informe y analisis que sale en el enunciado?

Informe y analisis
Debes hacer un informe que contenga un analisis teorico y empirico de tu solucion. En particular,  se espera lo siguiente:
Comparacion del desempeno al agregar las podas anteriormente mencionadas a la solucion. Utiliza tanto el tiempo de ejecucion como la cantidad de devoluciones como metrica de eficiencia.

**Comment by alopez7** [comment]
Cuando haces una asignación de una variable (un color) y te da un estado que no lleva a la solución, se hace una devolución (también conocido como undo)

**Comment by moralillo** [comment]
Al hacer el backtracking, uno toma un camino por ejemplo 1 - 2 - 3, luego se rompe y tiene que volver hasta el 1. La cantidad de devoluciones en ese caso sería 2 (una para el 3, otra para el 2), o esto cuenta como una sola devolución?

**Comment by alopez7** [comment]
Son 2
